# .goreleaser.yml
project_name: node

builds:
  - id: luxd-amd64
    main: ./main
    binary: luxd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
  
  - id: luxd-arm64
    main: ./main
    binary: luxd
    goos:
      - linux
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    tags:
      - noblst
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'