services:
  luxd:
    build:
      context: .
      dockerfile: Dockerfile
    image: lux-node:latest
    container_name: luxnet-node
    restart: unless-stopped
    ports:
      - "9650:9650"  # RPC port
      - "9651:9651"  # Staking port
      - "8546:8546"  # WebSocket port
    volumes:
      # Data persistence
      - lux_data:/luxd
      # Optional: Mount genesis file from host
      - ${GENESIS_FILE:-./genesis/genesis_mainnet.json}:/genesis.json:ro
      # Optional: Mount existing chain data for migration
      # - /home/z/.avalanche-cli/runs/network_current/node1/chainData/dnmzhuf6poM6PUNQCe7MWWfBdTJEnddhHRNXz2x7H6qSmyBEJ/db:/import-data:ro
    environment:
      # Network configuration
      NETWORK_ID: 96369
      DEV_MODE: "true"
      
      # API configuration
      API_ADMIN_ENABLED: "true"
      INDEX_ENABLED: "true"
      
      # Chain configuration
      ENABLE_AUTOMINING: "true"
      AUTOMINING_INTERVAL: "2s"
      LOG_LEVEL: "info"
      
      # Optional: Genesis file path
      GENESIS_FILE: "/genesis.json"
      
      # Optional: Import chain data path
      # IMPORT_CHAIN_DATA: "/import-data"
    networks:
      - hanzo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9650/ext/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Node exporter for monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: luxnet-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - hanzo-network
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro

  # Optional: Cadvisor for container monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: luxnet-cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - hanzo-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true

volumes:
  lux_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/z/lux-mainnet-data

networks:
  hanzo-network:
    external: true