version: '3.8'

services:
  luxd:
    image: ghcr.io/luxfi/node:latest
    networks:
      - lux-network
    ports:
      - target: 9630
        published: 9630
        protocol: tcp
        mode: host
      - target: 9631
        published: 9631
        protocol: tcp
        mode: host
    environment:
      - NETWORK_ID=96369
      - LOG_LEVEL=info
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=9630
      - STAKING_PORT=9631
    volumes:
      - luxd-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.labels.zone
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
        max_failure_ratio: 0.3
    secrets:
      - source: staking_key
        target: /keys/staking/staker.key
        mode: 0400
      - source: staking_cert
        target: /keys/staking/staker.crt
        mode: 0400
    configs:
      - source: luxd_config
        target: /app/config.json
        mode: 0444

  # Load balancer for RPC
  nginx:
    image: nginx:alpine
    networks:
      - lux-network
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

volumes:
  luxd-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-server.example.com,rw
      device: ":/exports/luxd-data"

networks:
  lux-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.9.0/24

secrets:
  staking_key:
    external: true
  staking_cert:
    external: true

configs:
  luxd_config:
    file: ./configs/luxd.json
  nginx_config:
    file: ./configs/nginx.conf