#!/bin/bash
# Script to create v2.0.0-alpha.1 tags for lux repositories

echo "This script will help create v2.0.0-alpha.1 tags for:"
echo "- luxfi/node/v2"
echo "- luxfi/evm/v2"
echo "- luxfi/cli/v2"
echo ""
echo "Steps to execute for each repository:"
echo ""

echo "1. For luxfi/node (current directory):"
echo "   git add ."
echo "   git commit -m 'Update to v2 module path for version 2.0.0-alpha.1'"
echo "   git tag v2.0.0-alpha.1"
echo "   git push origin dev"
echo "   git push origin v2.0.0-alpha.1"
echo ""

echo "2. For luxfi/evm:"
echo "   cd ../evm"
echo "   # Run the update script to change imports to v2"
echo "   bash update_evm_to_v2.sh"
echo "   git add ."
echo "   git commit -m 'Update to v2 module path for version 2.0.0-alpha.1'"
echo "   git tag v2.0.0-alpha.1"
echo "   git push origin dev"
echo "   git push origin v2.0.0-alpha.1"
echo ""

echo "3. For luxfi/cli:"
echo "   cd ../cli"
echo "   # Run the update script to change imports to v2"
echo "   bash update_cli_to_v2.sh"
echo "   git add ."
echo "   git commit -m 'Update to v2 module path for version 2.0.0-alpha.1'"
echo "   git tag v2.0.0-alpha.1"
echo "   git push origin dev"
echo "   git push origin v2.0.0-alpha.1"
echo ""

echo "After all repositories are tagged, come back to node and run:"
echo "   go mod tidy"
echo "   go build ./..."