rm -rf ./snowtest
rm -rf ./chain/snowmanmock
rm -rf ./chain/snowmantest
rm -rf ./engine/snowman
rm -rf ./protocols/snowball
rm -rf ./protocols/snowstorm
rm -rf ./protocols/snowball/binary_snowball.go
rm -rf ./protocols/snowball/binary_snowball_test.go
rm -rf ./protocols/snowball/binary_snowflake.go
rm -rf ./protocols/snowball/binary_snowflake_test.go
rm -rf ./protocols/snowball/nnary_snowball.go
rm -rf ./protocols/snowball/nnary_snowball_test.go
rm -rf ./protocols/snowball/nnary_snowflake.go
rm -rf ./protocols/snowball/nnary_snowflake_test.go
rm -rf ./protocols/snowball/snowflake_test.go
rm -rf ./protocols/snowball/unary_snowball.go
rm -rf ./protocols/snowball/unary_snowball_test.go
rm -rf ./protocols/snowball/unary_snowflake.go
rm -rf ./protocols/snowball/unary_snowflake_test.go
