apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: lux-localnet

labels:
- pairs:
    app.kubernetes.io/instance: localnet

patches:
- path: patches.yaml
