// Code generated by zip; DO NOT EDIT.

package upgrade

import (
	"fmt"
	"time"

	zap "github.com/zap-proto/go"
)

// ---- Config ------------------------------------------------------------

const (
	configXChainStopVertexIDAt = 0
	configEpochDurationAt      = 32
	configSize                 = 40
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Config)(nil)

// MarshalZAP writes Config from constant offsets.
func (x *Config) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(configSize + 256)
	ob := b.StartObject(configSize)
	ob.SetBytesFixed(configXChainStopVertexIDAt, x.XChainStopVertexID[:])
	ob.SetInt64(configEpochDurationAt, int64(x.EpochDuration))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Config out of the buffer that arrived.
func (x *Config) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Config: %w", err)
	}
	o := m.Root()
	copy(x.XChainStopVertexID[:], o.BytesFixed(configXChainStopVertexIDAt, 32))
	x.EpochDuration = time.Duration(o.Int64(configEpochDurationAt))
	return nil
}
