// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for rpcsigner compatibility

package signer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// PublicKeyRequest message
type PublicKeyRequest struct {
}

// PublicKeyResponse message
type PublicKeyResponse struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

// SignRequest message
type SignRequest struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

// SignResponse message
type SignResponse struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

// SignProofOfPossessionRequest message
type SignProofOfPossessionRequest struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

// SignProofOfPossessionResponse message
type SignProofOfPossessionResponse struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

// SignerClient is the client API for Signer service.
type SignerClient interface {
	PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	SignProofOfPossession(ctx context.Context, in *SignProofOfPossessionRequest, opts ...grpc.CallOption) (*SignProofOfPossessionResponse, error)
}

type signerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerClient(cc grpc.ClientConnInterface) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/signer.Signer/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/signer.Signer/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignProofOfPossession(ctx context.Context, in *SignProofOfPossessionRequest, opts ...grpc.CallOption) (*SignProofOfPossessionResponse, error) {
	out := new(SignProofOfPossessionResponse)
	err := c.cc.Invoke(ctx, "/signer.Signer/SignProofOfPossession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServer is the server API for Signer service.
type SignerServer interface {
	PublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	SignProofOfPossession(context.Context, *SignProofOfPossessionRequest) (*SignProofOfPossessionResponse, error)
}

// UnimplementedSignerServer should be embedded to have forward compatible implementations.
type UnimplementedSignerServer struct {
}

func (UnimplementedSignerServer) PublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKey not implemented")
}

func (UnimplementedSignerServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}

func (UnimplementedSignerServer) SignProofOfPossession(context.Context, *SignProofOfPossessionRequest) (*SignProofOfPossessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignProofOfPossession not implemented")
}

func RegisterSignerServer(s grpc.ServiceRegistrar, srv SignerServer) {
	// Stub implementation
}

// Reset for protobuf compatibility
func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return "" }
func (*SignRequest) ProtoMessage()    {}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return "" }
func (*SignResponse) ProtoMessage()    {}
func (m *SignResponse) GetSignature() []byte { return m.Signature }

// Reset for protobuf compatibility
func (m *PublicKeyRequest) Reset()         { *m = PublicKeyRequest{} }
func (m *PublicKeyRequest) String() string { return "" }
func (*PublicKeyRequest) ProtoMessage()    {}

func (m *PublicKeyResponse) Reset()         { *m = PublicKeyResponse{} }
func (m *PublicKeyResponse) String() string { return "" }
func (*PublicKeyResponse) ProtoMessage()    {}
func (m *PublicKeyResponse) GetPublicKey() []byte { return m.PublicKey }

func (m *SignProofOfPossessionRequest) Reset()         { *m = SignProofOfPossessionRequest{} }
func (m *SignProofOfPossessionRequest) String() string { return "" }
func (*SignProofOfPossessionRequest) ProtoMessage()    {}

func (m *SignProofOfPossessionResponse) Reset()         { *m = SignProofOfPossessionResponse{} }
func (m *SignProofOfPossessionResponse) String() string { return "" }
func (*SignProofOfPossessionResponse) ProtoMessage()    {}
func (m *SignProofOfPossessionResponse) GetSignature() []byte { return m.Signature }