// Code generated by zipdoc; DO NOT EDIT.

package platformvm

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /height", zip.Doc{
		Description: "Returns the height of the last accepted block.",
	})
}
