// Copyright (C) 2019-2025, Lux Industries, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package message

import (
	"fmt"

	"github.com/luxfi/ids"
	"github.com/luxfi/node/utils/crypto/bls"
	"github.com/luxfi/node/utils/hashing"
	"github.com/luxfi/node/vms/types"
)

type NetToL1ConversionValidatorData struct {
	NodeID       types.JSONByteSlice    `serialize:"true" json:"nodeID"`
	BLSPublicKey [bls.PublicKeyLen]byte `serialize:"true" json:"blsPublicKey"`
	Weight       uint64                 `serialize:"true" json:"weight"`
}

type NetToL1ConversionData struct {
	NetID       ids.ID                              `serialize:"true" json:"subnetID"`
	ManagerChainID ids.ID                              `serialize:"true" json:"managerChainID"`
	ManagerAddress types.JSONByteSlice                 `serialize:"true" json:"managerAddress"`
	Validators     []NetToL1ConversionValidatorData `serialize:"true" json:"validators"`
}

// NetToL1ConversionID creates a subnet conversion ID from the provided
// subnet conversion data.
func NetToL1ConversionID(data NetToL1ConversionData) (ids.ID, error) {
	bytes, err := Codec.Marshal(CodecVersion, &data)
	if err != nil {
		return ids.Empty, err
	}
	return hashing.ComputeHash256Array(bytes), nil
}

// NetToL1Conversion reports the summary of the subnet conversation that
// occurred on the P-chain.
type NetToL1Conversion struct {
	payload

	// ID of the subnet conversion. It is typically generated by calling
	// NetToL1ConversionID.
	ID ids.ID `serialize:"true" json:"id"`
}

// NewNetToL1Conversion creates a new initialized NetToL1Conversion.
func NewNetToL1Conversion(id ids.ID) (*NetToL1Conversion, error) {
	msg := &NetToL1Conversion{
		ID: id,
	}
	return msg, Initialize(msg)
}

// ParseNetToL1Conversion parses bytes into an initialized
// NetToL1Conversion.
func ParseNetToL1Conversion(b []byte) (*NetToL1Conversion, error) {
	payloadIntf, err := Parse(b)
	if err != nil {
		return nil, err
	}
	payload, ok := payloadIntf.(*NetToL1Conversion)
	if !ok {
		return nil, fmt.Errorf("%w: %T", ErrWrongType, payloadIntf)
	}
	return payload, nil
}
