// Code generated by zipdoc; DO NOT EDIT.

package indexer

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /accepted", zip.Doc{
		Description: "Returns whether this node has accepted and indexed a container.",
		Fields: map[string]string{
			"IsAcceptedArgs.id":             "ID is the container to ask about.",
			"IsAcceptedResponse.isAccepted": "IsAccepted is whether this node has accepted and indexed the container.",
		},
		Example: json.RawMessage(`{"id":"11111111111111111111111111111111LpoYY"}`),
	})
	zip.Describe("GET /container", zip.Doc{
		Description: "Returns the container with the given id.",
		Fields: map[string]string{
			"FormattedContainer.bytes":      "Bytes is the container, written in Encoding.",
			"FormattedContainer.encoding":   "Encoding is how Bytes is written.",
			"FormattedContainer.id":         "ID is the container's own id.",
			"FormattedContainer.index":      "Index is the container's position in the accepted order, from zero.",
			"FormattedContainer.timestamp":  "Timestamp is when this node accepted the container.",
			"GetContainerByIDArgs.encoding": "Encoding is how to write the container's bytes.",
			"GetContainerByIDArgs.id":       "ID is the container to read.",
			"Time.nanos":                    "Nanos is the nanosecond within that second.",
			"Time.offset":                   "Offset is seconds east of UTC.",
			"Time.seconds":                  "Seconds is seconds since the epoch.",
		},
		Example: json.RawMessage(`{"id":"11111111111111111111111111111111LpoYY","encoding":"hex"}`),
	})
	zip.Describe("GET /container/:index", zip.Doc{
		Description: "Returns the container accepted at the given position.",
		Fields: map[string]string{
			"FormattedContainer.bytes":         "Bytes is the container, written in Encoding.",
			"FormattedContainer.encoding":      "Encoding is how Bytes is written.",
			"FormattedContainer.id":            "ID is the container's own id.",
			"FormattedContainer.index":         "Index is the container's position in the accepted order, from zero.",
			"FormattedContainer.timestamp":     "Timestamp is when this node accepted the container.",
			"GetContainerByIndexArgs.encoding": "Encoding is how to write the container's bytes.",
			"GetContainerByIndexArgs.index":    "Index is the position to read, from zero.",
			"Time.nanos":                       "Nanos is the nanosecond within that second.",
			"Time.offset":                      "Offset is seconds east of UTC.",
			"Time.seconds":                     "Seconds is seconds since the epoch.",
		},
		Example: json.RawMessage(`{"index":"0","encoding":"hex"}`),
	})
	zip.Describe("GET /container/latest", zip.Doc{
		Description: "Returns the container this node accepted most recently.",
		Fields: map[string]string{
			"FormattedContainer.bytes":     "Bytes is the container, written in Encoding.",
			"FormattedContainer.encoding":  "Encoding is how Bytes is written.",
			"FormattedContainer.id":        "ID is the container's own id.",
			"FormattedContainer.index":     "Index is the container's position in the accepted order, from zero.",
			"FormattedContainer.timestamp": "Timestamp is when this node accepted the container.",
			"GetLastAcceptedArgs.encoding": "Encoding is how to write the container's bytes.",
			"Time.nanos":                   "Nanos is the nanosecond within that second.",
			"Time.offset":                  "Offset is seconds east of UTC.",
			"Time.seconds":                 "Seconds is seconds since the epoch.",
		},
		Example: json.RawMessage(`{"encoding":"hex"}`),
	})
	zip.Describe("GET /containers", zip.Doc{
		Description: "Returns the containers accepted at startIndex and after it.\n\nIt returns what it finds: asking past the last accepted one yields the\ncontainers before it and no error. numToFetch of zero yields none.",
		Fields: map[string]string{
			"FormattedContainer.bytes":             "Bytes is the container, written in Encoding.",
			"FormattedContainer.encoding":          "Encoding is how Bytes is written.",
			"FormattedContainer.id":                "ID is the container's own id.",
			"FormattedContainer.index":             "Index is the container's position in the accepted order, from zero.",
			"FormattedContainer.timestamp":         "Timestamp is when this node accepted the container.",
			"GetContainerRangeArgs.encoding":       "Encoding is how to write each container's bytes.",
			"GetContainerRangeArgs.numToFetch":     "NumToFetch is how many to read from there.",
			"GetContainerRangeArgs.startIndex":     "StartIndex is the first position to read, from zero.",
			"GetContainerRangeResponse.containers": "Containers are those read, in accepted order.",
			"Time.nanos":                           "Nanos is the nanosecond within that second.",
			"Time.offset":                          "Offset is seconds east of UTC.",
			"Time.seconds":                         "Seconds is seconds since the epoch.",
		},
		Example: json.RawMessage(`{"startIndex":"0","numToFetch":"2","encoding":"hex"}`),
	})
	zip.Describe("GET /index", zip.Doc{
		Description: "Returns a container's position in the accepted order.",
		Fields: map[string]string{
			"GetIndexArgs.id":        "ID is the container to locate.",
			"GetIndexResponse.index": "Index is the container's position in the accepted order, from zero.",
		},
		Example: json.RawMessage(`{"id":"11111111111111111111111111111111LpoYY"}`),
	})
}
