// Code generated by zip; DO NOT EDIT.

package json

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- Time --------------------------------------------------------------

const (
	timeSecondsAt = 0
	timeNanosAt   = 8
	timeOffsetAt  = 12
	timeSize      = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Time)(nil)

// MarshalZAP writes Time from constant offsets.
func (x *Time) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(timeSize + 256)
	ob := b.StartObject(timeSize)
	ob.SetInt64(timeSecondsAt, int64(x.Seconds))
	ob.SetInt32(timeNanosAt, int32(x.Nanos))
	ob.SetInt32(timeOffsetAt, int32(x.Offset))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Time out of the buffer that arrived.
func (x *Time) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Time: %w", err)
	}
	o := m.Root()
	x.Seconds = int64(o.Int64(timeSecondsAt))
	x.Nanos = int32(o.Int32(timeNanosAt))
	x.Offset = int32(o.Int32(timeOffsetAt))
	return nil
}
