// Code generated by zip; DO NOT EDIT.

package proposervm

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- GetProposedHeightArgs ---------------------------------------------

const (
	getProposedHeightArgsSize = 0
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetProposedHeightArgs)(nil)

// MarshalZAP writes GetProposedHeightArgs from constant offsets.
func (x *GetProposedHeightArgs) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getProposedHeightArgsSize + 256)
	ob := b.StartObject(getProposedHeightArgsSize)
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetProposedHeightArgs out of the buffer that arrived.
func (x *GetProposedHeightArgs) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetProposedHeightArgs: %w", err)
	}
	_ = m
	return nil
}

// ---- GetProposedHeightReply --------------------------------------------

const (
	getProposedHeightReplyProposedHeightAt = 0
	getProposedHeightReplySize             = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GetProposedHeightReply)(nil)

// MarshalZAP writes GetProposedHeightReply from constant offsets.
func (x *GetProposedHeightReply) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(getProposedHeightReplySize + 256)
	ob := b.StartObject(getProposedHeightReplySize)
	ob.SetUint64(getProposedHeightReplyProposedHeightAt, uint64(x.ProposedHeight))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GetProposedHeightReply out of the buffer that arrived.
func (x *GetProposedHeightReply) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GetProposedHeightReply: %w", err)
	}
	o := m.Root()
	x.ProposedHeight = uint64(o.Uint64(getProposedHeightReplyProposedHeightAt))
	return nil
}
