// SPDX-License-Identifier: BSD-3-Clause-Eco

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Where geth's checkout is, for the vectors borrowed from it. The default is
// the sibling layout every other Lux path resolves by.
func gethRoot() string {
	if d := os.Getenv("LUX_GETH"); d != "" {
		return d
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return filepath.Join(home, "work", "lux", "evm")
}

func emit(dir string) error {
	vectors, err := borrowed(gethRoot())
	if err != nil {
		return err
	}
	vectors = append(vectors, own()...)

	var v bytes.Buffer
	v.WriteString("# Lux precompile differential corpus.\n")
	v.WriteString("# Generated by conformance/precompile from the Go precompiles.\n")
	v.WriteString("# Most of it is borrowed: the inputs geth tests itself against are\n")
	v.WriteString("# the inputs the other two implementations should survive.\n")
	v.WriteString("# V\t<id>\t<address>\t<gas-limit>\t<input-hex>\n")
	seen := map[string]bool{}
	for _, vec := range vectors {
		if seen[vec.ID] {
			return fmt.Errorf("two vectors named %s", vec.ID)
		}
		seen[vec.ID] = true
		v.WriteString(vec.Line() + "\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "precompile_vectors.tsv"), v.Bytes(), 0o644); err != nil {
		return err
	}

	// The expectations are what Go said when it read the vectors back, not a
	// second opinion typed beside them.
	var e bytes.Buffer
	e.WriteString("# What the Go precompiles said when they read the corpus back.\n")
	e.WriteString("# R\t<id>\t<status>\t<gas-charged>\t<output-hex>\t<note>\n")
	for _, vec := range vectors {
		e.WriteString(run(vec).Line() + "\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "precompile_expected.tsv"), e.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Printf("%d vectors\n", len(vectors))
	return nil
}

// own is what the borrowed vectors do not reach: the addresses geth ships no
// test data for, the boundary between paying and not paying, and the two
// addresses where the three implementations are known to have made different
// decisions.
func own() []Vector {
	const plenty = 1 << 20
	v := []Vector{
		// The three precompiles with no test data of their own. An empty
		// input is a defined call to each of them, not a malformed one.
		{ID: "SHA256_EMPTY", Address: addr(0x02), Gas: plenty},
		{ID: "RIPEMD160_EMPTY", Address: addr(0x03), Gas: plenty},
		{ID: "IDENTITY_EMPTY", Address: addr(0x04), Gas: plenty},
		{ID: "SHA256_ABC", Address: addr(0x02), Gas: plenty, Input: []byte("abc")},
		{ID: "RIPEMD160_ABC", Address: addr(0x03), Gas: plenty, Input: []byte("abc")},
		{ID: "IDENTITY_ABC", Address: addr(0x04), Gas: plenty, Input: []byte("abc")},

		// Every precompile is asked for an empty input. Half of them refuse
		// it and half of them define it, and which half is which is exactly
		// the kind of thing three implementations can differ on quietly.
		{ID: "ECRECOVER_EMPTY", Address: addr(0x01), Gas: plenty},
		{ID: "MODEXP_EMPTY", Address: addr(0x05), Gas: plenty},
		{ID: "BN256ADD_EMPTY", Address: addr(0x06), Gas: plenty},
		{ID: "BN256MUL_EMPTY", Address: addr(0x07), Gas: plenty},
		{ID: "BN256PAIRING_EMPTY", Address: addr(0x08), Gas: plenty},
		{ID: "BLAKE2F_EMPTY", Address: addr(0x09), Gas: plenty},
		{ID: "KZG_EMPTY", Address: addr(0x0a), Gas: plenty},
		{ID: "BLS_G1ADD_EMPTY", Address: addr(0x0b), Gas: plenty},
		{ID: "BLS_G1MULTIEXP_EMPTY", Address: addr(0x0c), Gas: plenty},
		{ID: "BLS_G2ADD_EMPTY", Address: addr(0x0d), Gas: plenty},
		{ID: "BLS_G2MULTIEXP_EMPTY", Address: addr(0x0e), Gas: plenty},
		{ID: "BLS_PAIRING_EMPTY", Address: addr(0x0f), Gas: plenty},
		{ID: "BLS_MAPG1_EMPTY", Address: addr(0x10), Gas: plenty},
		{ID: "BLS_MAPG2_EMPTY", Address: addr(0x11), Gas: plenty},

		// Nothing serves these. An implementation that answers is claiming an
		// address the others do not, which is a fork whichever way it falls.
		// 0x0 is not among them: the dead-address module (LP-0150) is
		// registered there and intercepts transfers to it, which is a claim
		// the other two runtimes do not make and cannot be settled without a
		// chain to read.
		{ID: "UNCLAIMED_12", Address: addr(0x12), Gas: plenty},
		{ID: "UNCLAIMED_FF", Address: addr(0xff), Gas: plenty},
		{ID: "UNCLAIMED_0101", Address: addr(0x01, 0x01), Gas: plenty},

		// Lux's own, at the address Go serves. C++ reaches it only since
		// cevm learned to dispatch on a whole address rather than on the last
		// two bytes — 0x0300…0003 and ripemd160 share those. Rust serves no
		// Lux precompile at all, and says so.
		{ID: "AIVM_GENERATE", Address: addr(0x03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x03),
			Gas: 1 << 20, Input: aivmGenerate(10, 1, 7, 13, 2)},
		{ID: "AIVM_BAD_SELECTOR", Address: addr(0x03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x03),
			Gas: 1 << 20, Input: []byte{0x02, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1}},

		// 0x0100. Two implementations claim this address in Go alone: the
		// stock table charges 6900 and the Lux module charges 3450, and the
		// module wins because it is consulted first. Whether the other two
		// runtimes charge what the chain charges is the question.
		{ID: "P256_EMPTY", Address: addr(0x01, 0x00), Gas: plenty},
		{ID: "P256_WRONG_LENGTH", Address: addr(0x01, 0x00), Gas: plenty, Input: make([]byte, 159)},
		{ID: "P256_ZEROES", Address: addr(0x01, 0x00), Gas: plenty, Input: make([]byte, 160)},
	}

	// The gas boundary, for the fixed-price precompiles: exactly the charge,
	// and one below it. An implementation that charges a different price
	// crosses this boundary in a different place, which shows up here as a
	// verdict rather than as a number nobody reads.
	for _, b := range []struct {
		id      string
		address string
		cost    uint64
		input   []byte
	}{
		{"ECRECOVER", addr(0x01), 3000, make([]byte, 128)},
		{"SHA256", addr(0x02), 72, []byte("abc")},
		{"RIPEMD160", addr(0x03), 720, []byte("abc")},
		{"IDENTITY", addr(0x04), 18, []byte("abc")},
		{"P256", addr(0x01, 0x00), 3450, make([]byte, 160)},
	} {
		v = append(v,
			Vector{ID: b.id + "_GAS_EXACT", Address: b.address, Gas: b.cost, Input: b.input},
			Vector{ID: b.id + "_GAS_SHORT", Address: b.address, Gas: b.cost - 1, Input: b.input},
		)
	}
	return v
}

// aivmGenerate builds the inference precompile's calldata: the generate
// selector, how many tokens to produce, and the prompt — each a big-endian
// uint32, which is also how the answer comes back.
func aivmGenerate(nNew uint32, prompt ...uint32) []byte {
	out := []byte{0x01, 0x00, 0x00, 0x00}
	be := func(v uint32) { out = append(out, byte(v>>24), byte(v>>16), byte(v>>8), byte(v)) }
	be(nNew)
	for _, t := range prompt {
		be(t)
	}
	return out
}

// Kept so `emit` fails rather than writing a corpus with a name in it twice.
var _ = strings.ToUpper
