// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

//! ZAP schema `xchain.zap`, package `xchain`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use lux_zap::zap;

// Owners — field offsets, in bytes, and the fixed section's size.
pub const OWNERS_LOCKTIME: usize = 0;
pub const OWNERS_THRESHOLD: usize = 8;
pub const OWNERS_ADDRESSES: usize = 12;
pub const OWNERS_SIZE: usize = 20;

/// A view of a ZAP-encoded Owners. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Owners<'a> {
    o: zap::Object<'a>,
}

impl<'a> Owners<'a> {
    /// Take `data` as a Owners message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Owners {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Owners { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn locktime(&self) -> u64 {
        self.o.u64(OWNERS_LOCKTIME)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(OWNERS_THRESHOLD)
    }

    pub fn addresses(&self) -> zap::List<'a> {
        self.o.list_stride(OWNERS_ADDRESSES, 20)
    }
}

/// The field values [`new_owners`] writes.
#[derive(Clone, Copy, Debug)]
pub struct OwnersInput<'a> {
    pub locktime: u64,
    pub threshold: u32,
    pub addresses: &'a [[u8; 20]],
}

impl<'a> Default for OwnersInput<'a> {
    fn default() -> Self {
        OwnersInput {
            locktime: 0,
            threshold: 0,
            addresses: &[],
        }
    }
}

/// Write a Owners into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_owners(b: &mut zap::Builder, input: &OwnersInput<'_>) -> usize {
    let mut list_addresses = b.start_list();
    for elem in input.addresses {
        list_addresses.add_bytes(b, elem);
    }
    let at_addresses = list_addresses.finish_offset();
    let mut ob = b.start_object(OWNERS_SIZE);
    ob.set_u64(b, OWNERS_LOCKTIME, input.locktime);
    ob.set_u32(b, OWNERS_THRESHOLD, input.threshold);
    ob.set_list(b, OWNERS_ADDRESSES, at_addresses, input.addresses.len());
    ob.finish(b)
}

/// Write a Owners message and answer its bytes.
pub fn new_owners(input: &OwnersInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_owners(&mut b, input);
    b.set_root(at);
    b.finish()
}

// TransferOutput — field offsets, in bytes, and the fixed section's size.
pub const TRANSFER_OUTPUT_AMOUNT: usize = 0;
pub const TRANSFER_OUTPUT_LOCKTIME: usize = 8;
pub const TRANSFER_OUTPUT_THRESHOLD: usize = 16;
pub const TRANSFER_OUTPUT_ADDRESSES: usize = 20;
pub const TRANSFER_OUTPUT_SIZE: usize = 28;

/// A view of a ZAP-encoded TransferOutput. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferOutput<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferOutput<'a> {
    /// Take `data` as a TransferOutput message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferOutput {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferOutput { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(TRANSFER_OUTPUT_AMOUNT)
    }

    pub fn locktime(&self) -> u64 {
        self.o.u64(TRANSFER_OUTPUT_LOCKTIME)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(TRANSFER_OUTPUT_THRESHOLD)
    }

    pub fn addresses(&self) -> zap::List<'a> {
        self.o.list_stride(TRANSFER_OUTPUT_ADDRESSES, 20)
    }
}

/// The field values [`new_transfer_output`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferOutputInput<'a> {
    pub amount: u64,
    pub locktime: u64,
    pub threshold: u32,
    pub addresses: &'a [[u8; 20]],
}

impl<'a> Default for TransferOutputInput<'a> {
    fn default() -> Self {
        TransferOutputInput {
            amount: 0,
            locktime: 0,
            threshold: 0,
            addresses: &[],
        }
    }
}

/// Write a TransferOutput into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_transfer_output(b: &mut zap::Builder, input: &TransferOutputInput<'_>) -> usize {
    let mut list_addresses = b.start_list();
    for elem in input.addresses {
        list_addresses.add_bytes(b, elem);
    }
    let at_addresses = list_addresses.finish_offset();
    let mut ob = b.start_object(TRANSFER_OUTPUT_SIZE);
    ob.set_u64(b, TRANSFER_OUTPUT_AMOUNT, input.amount);
    ob.set_u64(b, TRANSFER_OUTPUT_LOCKTIME, input.locktime);
    ob.set_u32(b, TRANSFER_OUTPUT_THRESHOLD, input.threshold);
    ob.set_list(b, TRANSFER_OUTPUT_ADDRESSES, at_addresses, input.addresses.len());
    ob.finish(b)
}

/// Write a TransferOutput message and answer its bytes.
pub fn new_transfer_output(input: &TransferOutputInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_transfer_output(&mut b, input);
    b.set_root(at);
    b.finish()
}

// TransferInput — field offsets, in bytes, and the fixed section's size.
pub const TRANSFER_INPUT_AMOUNT: usize = 0;
pub const TRANSFER_INPUT_SIG_INDICES: usize = 8;
pub const TRANSFER_INPUT_SIZE: usize = 16;

/// A view of a ZAP-encoded TransferInput. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferInput<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferInput<'a> {
    /// Take `data` as a TransferInput message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferInput {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferInput { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(TRANSFER_INPUT_AMOUNT)
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list_stride(TRANSFER_INPUT_SIG_INDICES, 4)
    }
}

/// The field values [`new_transfer_input`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferInputInput<'a> {
    pub amount: u64,
    pub sig_indices: &'a [u32],
}

impl<'a> Default for TransferInputInput<'a> {
    fn default() -> Self {
        TransferInputInput {
            amount: 0,
            sig_indices: &[],
        }
    }
}

/// Write a TransferInput into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_transfer_input(b: &mut zap::Builder, input: &TransferInputInput<'_>) -> usize {
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_u32(b, *elem);
    }
    let at_sig_indices = list_sig_indices.finish_offset();
    let mut ob = b.start_object(TRANSFER_INPUT_SIZE);
    ob.set_u64(b, TRANSFER_INPUT_AMOUNT, input.amount);
    ob.set_list(b, TRANSFER_INPUT_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.finish(b)
}

/// Write a TransferInput message and answer its bytes.
pub fn new_transfer_input(input: &TransferInputInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_transfer_input(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Credential — field offsets, in bytes, and the fixed section's size.
pub const CREDENTIAL_SECURITY_LEVEL: usize = 0;
pub const CREDENTIAL_SIGNATURES: usize = 4;
pub const CREDENTIAL_PUB_KEYS: usize = 12;
pub const CREDENTIAL_SIZE: usize = 20;

/// A view of a ZAP-encoded Credential. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Credential<'a> {
    o: zap::Object<'a>,
}

impl<'a> Credential<'a> {
    /// Take `data` as a Credential message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Credential {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Credential { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn security_level(&self) -> u8 {
        self.o.u8(CREDENTIAL_SECURITY_LEVEL)
    }

    pub fn signatures(&self) -> zap::List<'a> {
        self.o.list_stride(CREDENTIAL_SIGNATURES, 1)
    }

    pub fn pub_keys(&self) -> zap::List<'a> {
        self.o.list_stride(CREDENTIAL_PUB_KEYS, 1)
    }
}

/// The field values [`new_credential`] writes.
#[derive(Clone, Copy, Debug)]
pub struct CredentialInput<'a> {
    pub security_level: u8,
    pub signatures: &'a [u8],
    pub pub_keys: &'a [u8],
}

impl<'a> Default for CredentialInput<'a> {
    fn default() -> Self {
        CredentialInput {
            security_level: 0,
            signatures: &[],
            pub_keys: &[],
        }
    }
}

/// Write a Credential into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_credential(b: &mut zap::Builder, input: &CredentialInput<'_>) -> usize {
    let mut list_signatures = b.start_list();
    for elem in input.signatures {
        list_signatures.add_u8(b, *elem);
    }
    let at_signatures = list_signatures.finish_offset();
    let mut list_pub_keys = b.start_list();
    for elem in input.pub_keys {
        list_pub_keys.add_u8(b, *elem);
    }
    let at_pub_keys = list_pub_keys.finish_offset();
    let mut ob = b.start_object(CREDENTIAL_SIZE);
    ob.set_u8(b, CREDENTIAL_SECURITY_LEVEL, input.security_level);
    ob.set_list(b, CREDENTIAL_SIGNATURES, at_signatures, input.signatures.len());
    ob.set_list(b, CREDENTIAL_PUB_KEYS, at_pub_keys, input.pub_keys.len());
    ob.finish(b)
}

/// Write a Credential message and answer its bytes.
pub fn new_credential(input: &CredentialInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_credential(&mut b, input);
    b.set_root(at);
    b.finish()
}

// MintOperation — field offsets, in bytes, and the fixed section's size.
pub const MINT_OPERATION_SIG_INDICES: usize = 0;
pub const MINT_OPERATION_MINT_OUTPUT: usize = 8;
pub const MINT_OPERATION_TRANSFER_OUTPUT: usize = 16;
pub const MINT_OPERATION_SIZE: usize = 24;

/// A view of a ZAP-encoded MintOperation. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct MintOperation<'a> {
    o: zap::Object<'a>,
}

impl<'a> MintOperation<'a> {
    /// Take `data` as a MintOperation message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(MintOperation {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        MintOperation { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list_stride(MINT_OPERATION_SIG_INDICES, 4)
    }

    pub fn mint_output(&self) -> &'a [u8] {
        self.o.bytes(MINT_OPERATION_MINT_OUTPUT)
    }

    pub fn transfer_output(&self) -> &'a [u8] {
        self.o.bytes(MINT_OPERATION_TRANSFER_OUTPUT)
    }
}

/// The field values [`new_mint_operation`] writes.
#[derive(Clone, Copy, Debug)]
pub struct MintOperationInput<'a> {
    pub sig_indices: &'a [u32],
    pub mint_output: &'a [u8],
    pub transfer_output: &'a [u8],
}

impl<'a> Default for MintOperationInput<'a> {
    fn default() -> Self {
        MintOperationInput {
            sig_indices: &[],
            mint_output: &[],
            transfer_output: &[],
        }
    }
}

/// Write a MintOperation into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_mint_operation(b: &mut zap::Builder, input: &MintOperationInput<'_>) -> usize {
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_u32(b, *elem);
    }
    let at_sig_indices = list_sig_indices.finish_offset();
    let mut ob = b.start_object(MINT_OPERATION_SIZE);
    ob.set_list(b, MINT_OPERATION_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_bytes(b, MINT_OPERATION_MINT_OUTPUT, input.mint_output);
    ob.set_bytes(b, MINT_OPERATION_TRANSFER_OUTPUT, input.transfer_output);
    ob.finish(b)
}

/// Write a MintOperation message and answer its bytes.
pub fn new_mint_operation(input: &MintOperationInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_mint_operation(&mut b, input);
    b.set_root(at);
    b.finish()
}

// BurnOperation — field offsets, in bytes, and the fixed section's size.
pub const BURN_OPERATION_SIG_INDICES: usize = 0;
pub const BURN_OPERATION_SIZE: usize = 8;

/// A view of a ZAP-encoded BurnOperation. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct BurnOperation<'a> {
    o: zap::Object<'a>,
}

impl<'a> BurnOperation<'a> {
    /// Take `data` as a BurnOperation message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(BurnOperation {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        BurnOperation { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list_stride(BURN_OPERATION_SIG_INDICES, 4)
    }
}

/// The field values [`new_burn_operation`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BurnOperationInput<'a> {
    pub sig_indices: &'a [u32],
}

impl<'a> Default for BurnOperationInput<'a> {
    fn default() -> Self {
        BurnOperationInput {
            sig_indices: &[],
        }
    }
}

/// Write a BurnOperation into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_burn_operation(b: &mut zap::Builder, input: &BurnOperationInput<'_>) -> usize {
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_u32(b, *elem);
    }
    let at_sig_indices = list_sig_indices.finish_offset();
    let mut ob = b.start_object(BURN_OPERATION_SIZE);
    ob.set_list(b, BURN_OPERATION_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.finish(b)
}

/// Write a BurnOperation message and answer its bytes.
pub fn new_burn_operation(input: &BurnOperationInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_burn_operation(&mut b, input);
    b.set_root(at);
    b.finish()
}

// NftMintOutput — field offsets, in bytes, and the fixed section's size.
pub const NFT_MINT_OUTPUT_GROUP: usize = 0;
pub const NFT_MINT_OUTPUT_LOCKTIME: usize = 4;
pub const NFT_MINT_OUTPUT_THRESHOLD: usize = 12;
pub const NFT_MINT_OUTPUT_ADDRESSES: usize = 16;
pub const NFT_MINT_OUTPUT_SIZE: usize = 24;

/// A view of a ZAP-encoded NftMintOutput. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct NftMintOutput<'a> {
    o: zap::Object<'a>,
}

impl<'a> NftMintOutput<'a> {
    /// Take `data` as a NftMintOutput message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(NftMintOutput {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        NftMintOutput { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn group(&self) -> u32 {
        self.o.u32(NFT_MINT_OUTPUT_GROUP)
    }

    pub fn locktime(&self) -> u64 {
        self.o.u64(NFT_MINT_OUTPUT_LOCKTIME)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(NFT_MINT_OUTPUT_THRESHOLD)
    }

    pub fn addresses(&self) -> zap::List<'a> {
        self.o.list_stride(NFT_MINT_OUTPUT_ADDRESSES, 20)
    }
}

/// The field values [`new_nft_mint_output`] writes.
#[derive(Clone, Copy, Debug)]
pub struct NftMintOutputInput<'a> {
    pub group: u32,
    pub locktime: u64,
    pub threshold: u32,
    pub addresses: &'a [[u8; 20]],
}

impl<'a> Default for NftMintOutputInput<'a> {
    fn default() -> Self {
        NftMintOutputInput {
            group: 0,
            locktime: 0,
            threshold: 0,
            addresses: &[],
        }
    }
}

/// Write a NftMintOutput into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_nft_mint_output(b: &mut zap::Builder, input: &NftMintOutputInput<'_>) -> usize {
    let mut list_addresses = b.start_list();
    for elem in input.addresses {
        list_addresses.add_bytes(b, elem);
    }
    let at_addresses = list_addresses.finish_offset();
    let mut ob = b.start_object(NFT_MINT_OUTPUT_SIZE);
    ob.set_u32(b, NFT_MINT_OUTPUT_GROUP, input.group);
    ob.set_u64(b, NFT_MINT_OUTPUT_LOCKTIME, input.locktime);
    ob.set_u32(b, NFT_MINT_OUTPUT_THRESHOLD, input.threshold);
    ob.set_list(b, NFT_MINT_OUTPUT_ADDRESSES, at_addresses, input.addresses.len());
    ob.finish(b)
}

/// Write a NftMintOutput message and answer its bytes.
pub fn new_nft_mint_output(input: &NftMintOutputInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_nft_mint_output(&mut b, input);
    b.set_root(at);
    b.finish()
}

// NftTransferOutput — field offsets, in bytes, and the fixed section's size.
pub const NFT_TRANSFER_OUTPUT_GROUP: usize = 0;
pub const NFT_TRANSFER_OUTPUT_LOCKTIME: usize = 4;
pub const NFT_TRANSFER_OUTPUT_THRESHOLD: usize = 12;
pub const NFT_TRANSFER_OUTPUT_ADDRESSES: usize = 16;
pub const NFT_TRANSFER_OUTPUT_PAYLOAD: usize = 24;
pub const NFT_TRANSFER_OUTPUT_SIZE: usize = 32;

/// A view of a ZAP-encoded NftTransferOutput. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct NftTransferOutput<'a> {
    o: zap::Object<'a>,
}

impl<'a> NftTransferOutput<'a> {
    /// Take `data` as a NftTransferOutput message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(NftTransferOutput {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        NftTransferOutput { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn group(&self) -> u32 {
        self.o.u32(NFT_TRANSFER_OUTPUT_GROUP)
    }

    pub fn locktime(&self) -> u64 {
        self.o.u64(NFT_TRANSFER_OUTPUT_LOCKTIME)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(NFT_TRANSFER_OUTPUT_THRESHOLD)
    }

    pub fn addresses(&self) -> zap::List<'a> {
        self.o.list_stride(NFT_TRANSFER_OUTPUT_ADDRESSES, 20)
    }

    pub fn payload(&self) -> &'a [u8] {
        self.o.bytes(NFT_TRANSFER_OUTPUT_PAYLOAD)
    }
}

/// The field values [`new_nft_transfer_output`] writes.
#[derive(Clone, Copy, Debug)]
pub struct NftTransferOutputInput<'a> {
    pub group: u32,
    pub locktime: u64,
    pub threshold: u32,
    pub addresses: &'a [[u8; 20]],
    pub payload: &'a [u8],
}

impl<'a> Default for NftTransferOutputInput<'a> {
    fn default() -> Self {
        NftTransferOutputInput {
            group: 0,
            locktime: 0,
            threshold: 0,
            addresses: &[],
            payload: &[],
        }
    }
}

/// Write a NftTransferOutput into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_nft_transfer_output(b: &mut zap::Builder, input: &NftTransferOutputInput<'_>) -> usize {
    let mut list_addresses = b.start_list();
    for elem in input.addresses {
        list_addresses.add_bytes(b, elem);
    }
    let at_addresses = list_addresses.finish_offset();
    let mut ob = b.start_object(NFT_TRANSFER_OUTPUT_SIZE);
    ob.set_u32(b, NFT_TRANSFER_OUTPUT_GROUP, input.group);
    ob.set_u64(b, NFT_TRANSFER_OUTPUT_LOCKTIME, input.locktime);
    ob.set_u32(b, NFT_TRANSFER_OUTPUT_THRESHOLD, input.threshold);
    ob.set_list(b, NFT_TRANSFER_OUTPUT_ADDRESSES, at_addresses, input.addresses.len());
    ob.set_bytes(b, NFT_TRANSFER_OUTPUT_PAYLOAD, input.payload);
    ob.finish(b)
}

/// Write a NftTransferOutput message and answer its bytes.
pub fn new_nft_transfer_output(input: &NftTransferOutputInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_nft_transfer_output(&mut b, input);
    b.set_root(at);
    b.finish()
}

// NftMintOperation — field offsets, in bytes, and the fixed section's size.
pub const NFT_MINT_OPERATION_SIG_INDICES: usize = 0;
pub const NFT_MINT_OPERATION_GROUP: usize = 8;
pub const NFT_MINT_OPERATION_PAYLOAD: usize = 12;
pub const NFT_MINT_OPERATION_OWNERS_COUNT: usize = 20;
pub const NFT_MINT_OPERATION_OWNERS_BYTES: usize = 24;
pub const NFT_MINT_OPERATION_PAD: usize = 32;
pub const NFT_MINT_OPERATION_SIZE: usize = 36;

/// A view of a ZAP-encoded NftMintOperation. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct NftMintOperation<'a> {
    o: zap::Object<'a>,
}

impl<'a> NftMintOperation<'a> {
    /// Take `data` as a NftMintOperation message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(NftMintOperation {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        NftMintOperation { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list_stride(NFT_MINT_OPERATION_SIG_INDICES, 4)
    }

    pub fn group(&self) -> u32 {
        self.o.u32(NFT_MINT_OPERATION_GROUP)
    }

    pub fn payload(&self) -> &'a [u8] {
        self.o.bytes(NFT_MINT_OPERATION_PAYLOAD)
    }

    pub fn owners_count(&self) -> u32 {
        self.o.u32(NFT_MINT_OPERATION_OWNERS_COUNT)
    }

    pub fn owners_bytes(&self) -> &'a [u8] {
        self.o.bytes(NFT_MINT_OPERATION_OWNERS_BYTES)
    }

    /// The 4 inline bytes at `NFT_MINT_OPERATION_PAD`; zeros if the span runs off the buffer.
    pub fn pad(&self) -> &'a [u8; 4] {
        self.o
            .bytes_fixed(NFT_MINT_OPERATION_PAD, 4)
            .try_into()
            .unwrap_or(&[0u8; 4])
    }
}

/// The field values [`new_nft_mint_operation`] writes.
#[derive(Clone, Copy, Debug)]
pub struct NftMintOperationInput<'a> {
    pub sig_indices: &'a [u32],
    pub group: u32,
    pub payload: &'a [u8],
    pub owners_count: u32,
    pub owners_bytes: &'a [u8],
    pub pad: &'a [u8; 4],
}

impl<'a> Default for NftMintOperationInput<'a> {
    fn default() -> Self {
        NftMintOperationInput {
            sig_indices: &[],
            group: 0,
            payload: &[],
            owners_count: 0,
            owners_bytes: &[],
            pad: &[0u8; 4],
        }
    }
}

/// Write a NftMintOperation into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_nft_mint_operation(b: &mut zap::Builder, input: &NftMintOperationInput<'_>) -> usize {
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_u32(b, *elem);
    }
    let at_sig_indices = list_sig_indices.finish_offset();
    let mut ob = b.start_object(NFT_MINT_OPERATION_SIZE);
    ob.set_list(b, NFT_MINT_OPERATION_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_u32(b, NFT_MINT_OPERATION_GROUP, input.group);
    ob.set_bytes(b, NFT_MINT_OPERATION_PAYLOAD, input.payload);
    ob.set_u32(b, NFT_MINT_OPERATION_OWNERS_COUNT, input.owners_count);
    ob.set_bytes(b, NFT_MINT_OPERATION_OWNERS_BYTES, input.owners_bytes);
    ob.set_bytes_fixed(b, NFT_MINT_OPERATION_PAD, input.pad);
    ob.finish(b)
}

/// Write a NftMintOperation message and answer its bytes.
pub fn new_nft_mint_operation(input: &NftMintOperationInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_nft_mint_operation(&mut b, input);
    b.set_root(at);
    b.finish()
}

// NftTransferOperation — field offsets, in bytes, and the fixed section's size.
pub const NFT_TRANSFER_OPERATION_SIG_INDICES: usize = 0;
pub const NFT_TRANSFER_OPERATION_OUTPUT: usize = 8;
pub const NFT_TRANSFER_OPERATION_SIZE: usize = 16;

/// A view of a ZAP-encoded NftTransferOperation. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct NftTransferOperation<'a> {
    o: zap::Object<'a>,
}

impl<'a> NftTransferOperation<'a> {
    /// Take `data` as a NftTransferOperation message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(NftTransferOperation {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        NftTransferOperation { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list_stride(NFT_TRANSFER_OPERATION_SIG_INDICES, 4)
    }

    pub fn output(&self) -> &'a [u8] {
        self.o.bytes(NFT_TRANSFER_OPERATION_OUTPUT)
    }
}

/// The field values [`new_nft_transfer_operation`] writes.
#[derive(Clone, Copy, Debug)]
pub struct NftTransferOperationInput<'a> {
    pub sig_indices: &'a [u32],
    pub output: &'a [u8],
}

impl<'a> Default for NftTransferOperationInput<'a> {
    fn default() -> Self {
        NftTransferOperationInput {
            sig_indices: &[],
            output: &[],
        }
    }
}

/// Write a NftTransferOperation into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_nft_transfer_operation(b: &mut zap::Builder, input: &NftTransferOperationInput<'_>) -> usize {
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_u32(b, *elem);
    }
    let at_sig_indices = list_sig_indices.finish_offset();
    let mut ob = b.start_object(NFT_TRANSFER_OPERATION_SIZE);
    ob.set_list(b, NFT_TRANSFER_OPERATION_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_bytes(b, NFT_TRANSFER_OPERATION_OUTPUT, input.output);
    ob.finish(b)
}

/// Write a NftTransferOperation message and answer its bytes.
pub fn new_nft_transfer_operation(input: &NftTransferOperationInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_nft_transfer_operation(&mut b, input);
    b.set_root(at);
    b.finish()
}

// TransferableOut — field offsets, in bytes, and the fixed section's size.
pub const TRANSFERABLE_OUT_ASSET: usize = 0;
pub const TRANSFERABLE_OUT_OUTPUT: usize = 32;
pub const TRANSFERABLE_OUT_SIZE: usize = 40;

/// A view of a ZAP-encoded TransferableOut. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferableOut<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferableOut<'a> {
    /// Take `data` as a TransferableOut message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferableOut {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferableOut { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `TRANSFERABLE_OUT_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_OUT_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output(&self) -> &'a [u8] {
        self.o.bytes(TRANSFERABLE_OUT_OUTPUT)
    }
}

/// The field values [`new_transferable_out`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferableOutInput<'a> {
    pub asset: &'a [u8; 32],
    pub output: &'a [u8],
}

impl<'a> Default for TransferableOutInput<'a> {
    fn default() -> Self {
        TransferableOutInput {
            asset: &[0u8; 32],
            output: &[],
        }
    }
}

/// Write a TransferableOut into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_transferable_out(b: &mut zap::Builder, input: &TransferableOutInput<'_>) -> usize {
    let mut ob = b.start_object(TRANSFERABLE_OUT_SIZE);
    ob.set_bytes_fixed(b, TRANSFERABLE_OUT_ASSET, input.asset);
    ob.set_bytes(b, TRANSFERABLE_OUT_OUTPUT, input.output);
    ob.finish(b)
}

/// Write a TransferableOut message and answer its bytes.
pub fn new_transferable_out(input: &TransferableOutInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_transferable_out(&mut b, input);
    b.set_root(at);
    b.finish()
}

// TransferableIn — field offsets, in bytes, and the fixed section's size.
pub const TRANSFERABLE_IN_TX_ID: usize = 0;
pub const TRANSFERABLE_IN_INDEX: usize = 32;
pub const TRANSFERABLE_IN_ASSET: usize = 36;
pub const TRANSFERABLE_IN_INPUT: usize = 68;
pub const TRANSFERABLE_IN_SIZE: usize = 76;

/// A view of a ZAP-encoded TransferableIn. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferableIn<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferableIn<'a> {
    /// Take `data` as a TransferableIn message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferableIn {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferableIn { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `TRANSFERABLE_IN_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_IN_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn index(&self) -> u32 {
        self.o.u32(TRANSFERABLE_IN_INDEX)
    }

    /// The 32 inline bytes at `TRANSFERABLE_IN_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_IN_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn input(&self) -> &'a [u8] {
        self.o.bytes(TRANSFERABLE_IN_INPUT)
    }
}

/// The field values [`new_transferable_in`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferableInInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub index: u32,
    pub asset: &'a [u8; 32],
    pub input: &'a [u8],
}

impl<'a> Default for TransferableInInput<'a> {
    fn default() -> Self {
        TransferableInInput {
            tx_id: &[0u8; 32],
            index: 0,
            asset: &[0u8; 32],
            input: &[],
        }
    }
}

/// Write a TransferableIn into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_transferable_in(b: &mut zap::Builder, input: &TransferableInInput<'_>) -> usize {
    let mut ob = b.start_object(TRANSFERABLE_IN_SIZE);
    ob.set_bytes_fixed(b, TRANSFERABLE_IN_TX_ID, input.tx_id);
    ob.set_u32(b, TRANSFERABLE_IN_INDEX, input.index);
    ob.set_bytes_fixed(b, TRANSFERABLE_IN_ASSET, input.asset);
    ob.set_bytes(b, TRANSFERABLE_IN_INPUT, input.input);
    ob.finish(b)
}

/// Write a TransferableIn message and answer its bytes.
pub fn new_transferable_in(input: &TransferableInInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_transferable_in(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Utxo — field offsets, in bytes, and the fixed section's size.
pub const UTXO_TX_ID: usize = 0;
pub const UTXO_INDEX: usize = 32;
pub const UTXO_ASSET: usize = 36;
pub const UTXO_OUTPUT: usize = 68;
pub const UTXO_SIZE: usize = 76;

/// A view of a ZAP-encoded Utxo. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Utxo<'a> {
    o: zap::Object<'a>,
}

impl<'a> Utxo<'a> {
    /// Take `data` as a Utxo message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Utxo {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Utxo { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `UTXO_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(UTXO_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn index(&self) -> u32 {
        self.o.u32(UTXO_INDEX)
    }

    /// The 32 inline bytes at `UTXO_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(UTXO_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output(&self) -> &'a [u8] {
        self.o.bytes(UTXO_OUTPUT)
    }
}

/// The field values [`new_utxo`] writes.
#[derive(Clone, Copy, Debug)]
pub struct UtxoInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub index: u32,
    pub asset: &'a [u8; 32],
    pub output: &'a [u8],
}

impl<'a> Default for UtxoInput<'a> {
    fn default() -> Self {
        UtxoInput {
            tx_id: &[0u8; 32],
            index: 0,
            asset: &[0u8; 32],
            output: &[],
        }
    }
}

/// Write a Utxo into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_utxo(b: &mut zap::Builder, input: &UtxoInput<'_>) -> usize {
    let mut ob = b.start_object(UTXO_SIZE);
    ob.set_bytes_fixed(b, UTXO_TX_ID, input.tx_id);
    ob.set_u32(b, UTXO_INDEX, input.index);
    ob.set_bytes_fixed(b, UTXO_ASSET, input.asset);
    ob.set_bytes(b, UTXO_OUTPUT, input.output);
    ob.finish(b)
}

/// Write a Utxo message and answer its bytes.
pub fn new_utxo(input: &UtxoInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_utxo(&mut b, input);
    b.set_root(at);
    b.finish()
}

// UtxoId — field offsets, in bytes, and the fixed section's size.
pub const UTXO_ID_TX_ID: usize = 0;
pub const UTXO_ID_INDEX: usize = 32;
pub const UTXO_ID_SIZE: usize = 36;

/// A view of a ZAP-encoded UtxoId. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct UtxoId<'a> {
    o: zap::Object<'a>,
}

impl<'a> UtxoId<'a> {
    /// Take `data` as a UtxoId message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(UtxoId {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        UtxoId { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `UTXO_ID_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(UTXO_ID_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn index(&self) -> u32 {
        self.o.u32(UTXO_ID_INDEX)
    }
}

/// The field values [`new_utxo_id`] writes.
#[derive(Clone, Copy, Debug)]
pub struct UtxoIdInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub index: u32,
}

impl<'a> Default for UtxoIdInput<'a> {
    fn default() -> Self {
        UtxoIdInput {
            tx_id: &[0u8; 32],
            index: 0,
        }
    }
}

/// UtxoId as the UTXO_ID_SIZE bytes one element of a list holds.
pub fn pack_utxo_id(input: &UtxoIdInput<'_>) -> [u8; UTXO_ID_SIZE] {
    let mut r = [0u8; UTXO_ID_SIZE];
    r[UTXO_ID_TX_ID..UTXO_ID_TX_ID + 32].copy_from_slice(input.tx_id);
    r[UTXO_ID_INDEX..UTXO_ID_INDEX + 4].copy_from_slice(&input.index.to_le_bytes());
    r
}

/// Write a UtxoId into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_utxo_id(b: &mut zap::Builder, input: &UtxoIdInput<'_>) -> usize {
    let mut ob = b.start_object(UTXO_ID_SIZE);
    ob.set_bytes_fixed(b, UTXO_ID_TX_ID, input.tx_id);
    ob.set_u32(b, UTXO_ID_INDEX, input.index);
    ob.finish(b)
}

/// Write a UtxoId message and answer its bytes.
pub fn new_utxo_id(input: &UtxoIdInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_utxo_id(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Envelope — field offsets, in bytes, and the fixed section's size.
pub const ENVELOPE_NETWORK: usize = 0;
pub const ENVELOPE_CHAIN: usize = 8;
pub const ENVELOPE_OUTS: usize = 40;
pub const ENVELOPE_INS: usize = 48;
pub const ENVELOPE_MEMO: usize = 56;
pub const ENVELOPE_SIZE: usize = 64;

/// A view of a ZAP-encoded Envelope. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Envelope<'a> {
    o: zap::Object<'a>,
}

impl<'a> Envelope<'a> {
    /// Take `data` as a Envelope message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Envelope {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Envelope { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn network(&self) -> u32 {
        self.o.u32(ENVELOPE_NETWORK)
    }

    /// The 32 inline bytes at `ENVELOPE_CHAIN`; zeros if the span runs off the buffer.
    pub fn chain(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(ENVELOPE_CHAIN, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> zap::List<'a> {
        self.o.list_stride(ENVELOPE_OUTS, 4)
    }

    /// Element `i` of `outs`, the object its pointer names.
    pub fn outs_at(&self, i: usize) -> TransferableOut<'a> {
        TransferableOut::new(self.outs().object_ptr(i))
    }

    pub fn ins(&self) -> zap::List<'a> {
        self.o.list_stride(ENVELOPE_INS, 4)
    }

    /// Element `i` of `ins`, the object its pointer names.
    pub fn ins_at(&self, i: usize) -> TransferableIn<'a> {
        TransferableIn::new(self.ins().object_ptr(i))
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(ENVELOPE_MEMO)
    }
}

/// The field values [`new_envelope`] writes.
#[derive(Clone, Copy, Debug)]
pub struct EnvelopeInput<'a> {
    pub network: u32,
    pub chain: &'a [u8; 32],
    pub outs: &'a [TransferableOutInput<'a>],
    pub ins: &'a [TransferableInInput<'a>],
    pub memo: &'a [u8],
}

impl<'a> Default for EnvelopeInput<'a> {
    fn default() -> Self {
        EnvelopeInput {
            network: 0,
            chain: &[0u8; 32],
            outs: &[],
            ins: &[],
            memo: &[],
        }
    }
}

/// Write a Envelope into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_envelope(b: &mut zap::Builder, input: &EnvelopeInput<'_>) -> usize {
    let mut offs_outs: Vec<usize> = Vec::with_capacity(input.outs.len());
    for elem in input.outs {
        offs_outs.push(put_transferable_out(b, elem));
    }
    let mut offs_ins: Vec<usize> = Vec::with_capacity(input.ins.len());
    for elem in input.ins {
        offs_ins.push(put_transferable_in(b, elem));
    }
    let mut list_outs = b.start_list();
    for at in &offs_outs {
        list_outs.add_object_ptr(b, *at);
    }
    let at_outs = list_outs.finish_offset();
    let mut list_ins = b.start_list();
    for at in &offs_ins {
        list_ins.add_object_ptr(b, *at);
    }
    let at_ins = list_ins.finish_offset();
    let mut ob = b.start_object(ENVELOPE_SIZE);
    ob.set_u32(b, ENVELOPE_NETWORK, input.network);
    ob.set_bytes_fixed(b, ENVELOPE_CHAIN, input.chain);
    ob.set_list(b, ENVELOPE_OUTS, at_outs, input.outs.len());
    ob.set_list(b, ENVELOPE_INS, at_ins, input.ins.len());
    ob.set_bytes(b, ENVELOPE_MEMO, input.memo);
    ob.finish(b)
}

/// Write a Envelope message and answer its bytes.
pub fn new_envelope(input: &EnvelopeInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_envelope(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Signed — field offsets, in bytes, and the fixed section's size.
pub const SIGNED_UNSIGNED: usize = 0;
pub const SIGNED_CREDENTIAL_COUNT: usize = 8;
pub const SIGNED_CREDENTIAL_BYTES: usize = 12;
pub const SIGNED_SIZE: usize = 20;

/// A view of a ZAP-encoded Signed. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Signed<'a> {
    o: zap::Object<'a>,
}

impl<'a> Signed<'a> {
    /// Take `data` as a Signed message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Signed {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Signed { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn unsigned(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_UNSIGNED)
    }

    pub fn credential_count(&self) -> u32 {
        self.o.u32(SIGNED_CREDENTIAL_COUNT)
    }

    pub fn credential_bytes(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_CREDENTIAL_BYTES)
    }
}

/// The field values [`new_signed`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SignedInput<'a> {
    pub unsigned: &'a [u8],
    pub credential_count: u32,
    pub credential_bytes: &'a [u8],
}

impl<'a> Default for SignedInput<'a> {
    fn default() -> Self {
        SignedInput {
            unsigned: &[],
            credential_count: 0,
            credential_bytes: &[],
        }
    }
}

/// Write a Signed into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_signed(b: &mut zap::Builder, input: &SignedInput<'_>) -> usize {
    let mut ob = b.start_object(SIGNED_SIZE);
    ob.set_bytes(b, SIGNED_UNSIGNED, input.unsigned);
    ob.set_u32(b, SIGNED_CREDENTIAL_COUNT, input.credential_count);
    ob.set_bytes(b, SIGNED_CREDENTIAL_BYTES, input.credential_bytes);
    ob.finish(b)
}

/// Write a Signed message and answer its bytes.
pub fn new_signed(input: &SignedInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_signed(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Base — field offsets, in bytes, and the fixed section's size.
pub const BASE_KIND: usize = 0;
pub const BASE_BASE: usize = 8;
pub const BASE_SIZE: usize = 16;

/// A view of a ZAP-encoded Base. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Base<'a> {
    o: zap::Object<'a>,
}

impl<'a> Base<'a> {
    /// Take `data` as a Base message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Base {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Base { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(BASE_KIND)
    }

    pub fn base(&self) -> &'a [u8] {
        self.o.bytes(BASE_BASE)
    }
}

/// The field values [`new_base`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BaseInput<'a> {
    pub kind: u8,
    pub base: &'a [u8],
}

impl<'a> Default for BaseInput<'a> {
    fn default() -> Self {
        BaseInput {
            kind: 0,
            base: &[],
        }
    }
}

/// Write a Base into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_base(b: &mut zap::Builder, input: &BaseInput<'_>) -> usize {
    let mut ob = b.start_object(BASE_SIZE);
    ob.set_u8(b, BASE_KIND, input.kind);
    ob.set_bytes(b, BASE_BASE, input.base);
    ob.finish(b)
}

/// Write a Base message and answer its bytes.
pub fn new_base(input: &BaseInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_base(&mut b, input);
    b.set_root(at);
    b.finish()
}

// CreateAsset — field offsets, in bytes, and the fixed section's size.
pub const CREATE_ASSET_KIND: usize = 0;
pub const CREATE_ASSET_BASE: usize = 8;
pub const CREATE_ASSET_NAME: usize = 16;
pub const CREATE_ASSET_SYMBOL: usize = 24;
pub const CREATE_ASSET_DENOMINATOR: usize = 32;
pub const CREATE_ASSET_STATE_LENS: usize = 36;
pub const CREATE_ASSET_STATE_BLOB: usize = 44;
pub const CREATE_ASSET_SIZE: usize = 52;

/// A view of a ZAP-encoded CreateAsset. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct CreateAsset<'a> {
    o: zap::Object<'a>,
}

impl<'a> CreateAsset<'a> {
    /// Take `data` as a CreateAsset message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(CreateAsset {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        CreateAsset { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(CREATE_ASSET_KIND)
    }

    pub fn base(&self) -> &'a [u8] {
        self.o.bytes(CREATE_ASSET_BASE)
    }

    pub fn name(&self) -> &'a [u8] {
        self.o.bytes(CREATE_ASSET_NAME)
    }

    pub fn symbol(&self) -> &'a [u8] {
        self.o.bytes(CREATE_ASSET_SYMBOL)
    }

    pub fn denominator(&self) -> u8 {
        self.o.u8(CREATE_ASSET_DENOMINATOR)
    }

    pub fn state_lens(&self) -> zap::List<'a> {
        self.o.list_stride(CREATE_ASSET_STATE_LENS, 4)
    }

    pub fn state_blob(&self) -> &'a [u8] {
        self.o.bytes(CREATE_ASSET_STATE_BLOB)
    }
}

/// The field values [`new_create_asset`] writes.
#[derive(Clone, Copy, Debug)]
pub struct CreateAssetInput<'a> {
    pub kind: u8,
    pub base: &'a [u8],
    pub name: &'a [u8],
    pub symbol: &'a [u8],
    pub denominator: u8,
    pub state_lens: &'a [u32],
    pub state_blob: &'a [u8],
}

impl<'a> Default for CreateAssetInput<'a> {
    fn default() -> Self {
        CreateAssetInput {
            kind: 0,
            base: &[],
            name: &[],
            symbol: &[],
            denominator: 0,
            state_lens: &[],
            state_blob: &[],
        }
    }
}

/// Write a CreateAsset into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_create_asset(b: &mut zap::Builder, input: &CreateAssetInput<'_>) -> usize {
    let mut list_state_lens = b.start_list();
    for elem in input.state_lens {
        list_state_lens.add_u32(b, *elem);
    }
    let at_state_lens = list_state_lens.finish_offset();
    let mut ob = b.start_object(CREATE_ASSET_SIZE);
    ob.set_u8(b, CREATE_ASSET_KIND, input.kind);
    ob.set_bytes(b, CREATE_ASSET_BASE, input.base);
    ob.set_bytes(b, CREATE_ASSET_NAME, input.name);
    ob.set_bytes(b, CREATE_ASSET_SYMBOL, input.symbol);
    ob.set_u8(b, CREATE_ASSET_DENOMINATOR, input.denominator);
    ob.set_list(b, CREATE_ASSET_STATE_LENS, at_state_lens, input.state_lens.len());
    ob.set_bytes(b, CREATE_ASSET_STATE_BLOB, input.state_blob);
    ob.finish(b)
}

/// Write a CreateAsset message and answer its bytes.
pub fn new_create_asset(input: &CreateAssetInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_create_asset(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Operate — field offsets, in bytes, and the fixed section's size.
pub const OPERATE_KIND: usize = 0;
pub const OPERATE_BASE: usize = 8;
pub const OPERATE_OP_LENS: usize = 16;
pub const OPERATE_OP_BLOB: usize = 24;
pub const OPERATE_SIZE: usize = 32;

/// A view of a ZAP-encoded Operate. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Operate<'a> {
    o: zap::Object<'a>,
}

impl<'a> Operate<'a> {
    /// Take `data` as a Operate message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Operate {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Operate { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(OPERATE_KIND)
    }

    pub fn base(&self) -> &'a [u8] {
        self.o.bytes(OPERATE_BASE)
    }

    pub fn op_lens(&self) -> zap::List<'a> {
        self.o.list_stride(OPERATE_OP_LENS, 4)
    }

    pub fn op_blob(&self) -> &'a [u8] {
        self.o.bytes(OPERATE_OP_BLOB)
    }
}

/// The field values [`new_operate`] writes.
#[derive(Clone, Copy, Debug)]
pub struct OperateInput<'a> {
    pub kind: u8,
    pub base: &'a [u8],
    pub op_lens: &'a [u32],
    pub op_blob: &'a [u8],
}

impl<'a> Default for OperateInput<'a> {
    fn default() -> Self {
        OperateInput {
            kind: 0,
            base: &[],
            op_lens: &[],
            op_blob: &[],
        }
    }
}

/// Write a Operate into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_operate(b: &mut zap::Builder, input: &OperateInput<'_>) -> usize {
    let mut list_op_lens = b.start_list();
    for elem in input.op_lens {
        list_op_lens.add_u32(b, *elem);
    }
    let at_op_lens = list_op_lens.finish_offset();
    let mut ob = b.start_object(OPERATE_SIZE);
    ob.set_u8(b, OPERATE_KIND, input.kind);
    ob.set_bytes(b, OPERATE_BASE, input.base);
    ob.set_list(b, OPERATE_OP_LENS, at_op_lens, input.op_lens.len());
    ob.set_bytes(b, OPERATE_OP_BLOB, input.op_blob);
    ob.finish(b)
}

/// Write a Operate message and answer its bytes.
pub fn new_operate(input: &OperateInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_operate(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Import — field offsets, in bytes, and the fixed section's size.
pub const IMPORT_KIND: usize = 0;
pub const IMPORT_BASE: usize = 8;
pub const IMPORT_SOURCE: usize = 16;
pub const IMPORT_INS: usize = 48;
pub const IMPORT_SIZE: usize = 56;

/// A view of a ZAP-encoded Import. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Import<'a> {
    o: zap::Object<'a>,
}

impl<'a> Import<'a> {
    /// Take `data` as a Import message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Import {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Import { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(IMPORT_KIND)
    }

    pub fn base(&self) -> &'a [u8] {
        self.o.bytes(IMPORT_BASE)
    }

    /// The 32 inline bytes at `IMPORT_SOURCE`; zeros if the span runs off the buffer.
    pub fn source(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IMPORT_SOURCE, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn ins(&self) -> zap::List<'a> {
        self.o.list_stride(IMPORT_INS, 4)
    }

    /// Element `i` of `ins`, the object its pointer names.
    pub fn ins_at(&self, i: usize) -> TransferableIn<'a> {
        TransferableIn::new(self.ins().object_ptr(i))
    }
}

/// The field values [`new_import`] writes.
#[derive(Clone, Copy, Debug)]
pub struct ImportInput<'a> {
    pub kind: u8,
    pub base: &'a [u8],
    pub source: &'a [u8; 32],
    pub ins: &'a [TransferableInInput<'a>],
}

impl<'a> Default for ImportInput<'a> {
    fn default() -> Self {
        ImportInput {
            kind: 0,
            base: &[],
            source: &[0u8; 32],
            ins: &[],
        }
    }
}

/// Write a Import into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_import(b: &mut zap::Builder, input: &ImportInput<'_>) -> usize {
    let mut offs_ins: Vec<usize> = Vec::with_capacity(input.ins.len());
    for elem in input.ins {
        offs_ins.push(put_transferable_in(b, elem));
    }
    let mut list_ins = b.start_list();
    for at in &offs_ins {
        list_ins.add_object_ptr(b, *at);
    }
    let at_ins = list_ins.finish_offset();
    let mut ob = b.start_object(IMPORT_SIZE);
    ob.set_u8(b, IMPORT_KIND, input.kind);
    ob.set_bytes(b, IMPORT_BASE, input.base);
    ob.set_bytes_fixed(b, IMPORT_SOURCE, input.source);
    ob.set_list(b, IMPORT_INS, at_ins, input.ins.len());
    ob.finish(b)
}

/// Write a Import message and answer its bytes.
pub fn new_import(input: &ImportInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_import(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Export — field offsets, in bytes, and the fixed section's size.
pub const EXPORT_KIND: usize = 0;
pub const EXPORT_BASE: usize = 8;
pub const EXPORT_DESTINATION: usize = 16;
pub const EXPORT_OUTS: usize = 48;
pub const EXPORT_SIZE: usize = 56;

/// A view of a ZAP-encoded Export. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Export<'a> {
    o: zap::Object<'a>,
}

impl<'a> Export<'a> {
    /// Take `data` as a Export message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Export {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Export { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(EXPORT_KIND)
    }

    pub fn base(&self) -> &'a [u8] {
        self.o.bytes(EXPORT_BASE)
    }

    /// The 32 inline bytes at `EXPORT_DESTINATION`; zeros if the span runs off the buffer.
    pub fn destination(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(EXPORT_DESTINATION, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> zap::List<'a> {
        self.o.list_stride(EXPORT_OUTS, 4)
    }

    /// Element `i` of `outs`, the object its pointer names.
    pub fn outs_at(&self, i: usize) -> TransferableOut<'a> {
        TransferableOut::new(self.outs().object_ptr(i))
    }
}

/// The field values [`new_export`] writes.
#[derive(Clone, Copy, Debug)]
pub struct ExportInput<'a> {
    pub kind: u8,
    pub base: &'a [u8],
    pub destination: &'a [u8; 32],
    pub outs: &'a [TransferableOutInput<'a>],
}

impl<'a> Default for ExportInput<'a> {
    fn default() -> Self {
        ExportInput {
            kind: 0,
            base: &[],
            destination: &[0u8; 32],
            outs: &[],
        }
    }
}

/// Write a Export into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_export(b: &mut zap::Builder, input: &ExportInput<'_>) -> usize {
    let mut offs_outs: Vec<usize> = Vec::with_capacity(input.outs.len());
    for elem in input.outs {
        offs_outs.push(put_transferable_out(b, elem));
    }
    let mut list_outs = b.start_list();
    for at in &offs_outs {
        list_outs.add_object_ptr(b, *at);
    }
    let at_outs = list_outs.finish_offset();
    let mut ob = b.start_object(EXPORT_SIZE);
    ob.set_u8(b, EXPORT_KIND, input.kind);
    ob.set_bytes(b, EXPORT_BASE, input.base);
    ob.set_bytes_fixed(b, EXPORT_DESTINATION, input.destination);
    ob.set_list(b, EXPORT_OUTS, at_outs, input.outs.len());
    ob.finish(b)
}

/// Write a Export message and answer its bytes.
pub fn new_export(input: &ExportInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_export(&mut b, input);
    b.set_root(at);
    b.finish()
}

// InitialState — field offsets, in bytes, and the fixed section's size.
pub const INITIAL_STATE_FX_INDEX: usize = 0;
pub const INITIAL_STATE_OUT_LENS: usize = 4;
pub const INITIAL_STATE_OUT_BLOB: usize = 12;
pub const INITIAL_STATE_SIZE: usize = 20;

/// A view of a ZAP-encoded InitialState. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct InitialState<'a> {
    o: zap::Object<'a>,
}

impl<'a> InitialState<'a> {
    /// Take `data` as a InitialState message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(InitialState {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        InitialState { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn fx_index(&self) -> u32 {
        self.o.u32(INITIAL_STATE_FX_INDEX)
    }

    pub fn out_lens(&self) -> zap::List<'a> {
        self.o.list_stride(INITIAL_STATE_OUT_LENS, 4)
    }

    pub fn out_blob(&self) -> &'a [u8] {
        self.o.bytes(INITIAL_STATE_OUT_BLOB)
    }
}

/// The field values [`new_initial_state`] writes.
#[derive(Clone, Copy, Debug)]
pub struct InitialStateInput<'a> {
    pub fx_index: u32,
    pub out_lens: &'a [u32],
    pub out_blob: &'a [u8],
}

impl<'a> Default for InitialStateInput<'a> {
    fn default() -> Self {
        InitialStateInput {
            fx_index: 0,
            out_lens: &[],
            out_blob: &[],
        }
    }
}

/// Write a InitialState into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_initial_state(b: &mut zap::Builder, input: &InitialStateInput<'_>) -> usize {
    let mut list_out_lens = b.start_list();
    for elem in input.out_lens {
        list_out_lens.add_u32(b, *elem);
    }
    let at_out_lens = list_out_lens.finish_offset();
    let mut ob = b.start_object(INITIAL_STATE_SIZE);
    ob.set_u32(b, INITIAL_STATE_FX_INDEX, input.fx_index);
    ob.set_list(b, INITIAL_STATE_OUT_LENS, at_out_lens, input.out_lens.len());
    ob.set_bytes(b, INITIAL_STATE_OUT_BLOB, input.out_blob);
    ob.finish(b)
}

/// Write a InitialState message and answer its bytes.
pub fn new_initial_state(input: &InitialStateInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_initial_state(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Operation — field offsets, in bytes, and the fixed section's size.
pub const OPERATION_ASSET: usize = 0;
pub const OPERATION_UTXO_IDS: usize = 32;
pub const OPERATION_FX_OP: usize = 40;
pub const OPERATION_SIZE: usize = 48;

/// A view of a ZAP-encoded Operation. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Operation<'a> {
    o: zap::Object<'a>,
}

impl<'a> Operation<'a> {
    /// Take `data` as a Operation message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Operation {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Operation { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `OPERATION_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(OPERATION_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn utxo_ids(&self) -> zap::List<'a> {
        self.o.list_stride(OPERATION_UTXO_IDS, 36)
    }

    /// Element `i` of `utxo_ids`. Out of range answers the zero view.
    pub fn utxo_ids_at(&self, i: usize) -> UtxoId<'a> {
        UtxoId::new(self.utxo_ids().object(i, UTXO_ID_SIZE))
    }

    pub fn fx_op(&self) -> &'a [u8] {
        self.o.bytes(OPERATION_FX_OP)
    }
}

/// The field values [`new_operation`] writes.
#[derive(Clone, Copy, Debug)]
pub struct OperationInput<'a> {
    pub asset: &'a [u8; 32],
    pub utxo_ids: &'a [&'a [u8]],
    pub fx_op: &'a [u8],
}

impl<'a> Default for OperationInput<'a> {
    fn default() -> Self {
        OperationInput {
            asset: &[0u8; 32],
            utxo_ids: &[],
            fx_op: &[],
        }
    }
}

/// Write a Operation into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_operation(b: &mut zap::Builder, input: &OperationInput<'_>) -> usize {
    let mut list_utxo_ids = b.start_list();
    for elem in input.utxo_ids {
        list_utxo_ids.add_bytes(b, elem);
    }
    let at_utxo_ids = list_utxo_ids.finish_offset();
    let mut ob = b.start_object(OPERATION_SIZE);
    ob.set_bytes_fixed(b, OPERATION_ASSET, input.asset);
    ob.set_list(b, OPERATION_UTXO_IDS, at_utxo_ids, input.utxo_ids.len());
    ob.set_bytes(b, OPERATION_FX_OP, input.fx_op);
    ob.finish(b)
}

/// Write a Operation message and answer its bytes.
pub fn new_operation(input: &OperationInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_operation(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Block — field offsets, in bytes, and the fixed section's size.
pub const BLOCK_PARENT: usize = 0;
pub const BLOCK_HEIGHT: usize = 32;
pub const BLOCK_TIME: usize = 40;
pub const BLOCK_ROOT: usize = 48;
pub const BLOCK_TX_LENGTHS: usize = 80;
pub const BLOCK_TX_BLOB: usize = 88;
pub const BLOCK_SIZE: usize = 96;

/// A view of a ZAP-encoded Block. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Block<'a> {
    o: zap::Object<'a>,
}

impl<'a> Block<'a> {
    /// Take `data` as a Block message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Block {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Block { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `BLOCK_PARENT`; zeros if the span runs off the buffer.
    pub fn parent(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_PARENT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn height(&self) -> u64 {
        self.o.u64(BLOCK_HEIGHT)
    }

    pub fn time(&self) -> u64 {
        self.o.u64(BLOCK_TIME)
    }

    /// The 32 inline bytes at `BLOCK_ROOT`; zeros if the span runs off the buffer.
    pub fn root(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_ROOT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn tx_lengths(&self) -> zap::List<'a> {
        self.o.list_stride(BLOCK_TX_LENGTHS, 4)
    }

    pub fn tx_blob(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_TX_BLOB)
    }
}

/// The field values [`new_block`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BlockInput<'a> {
    pub parent: &'a [u8; 32],
    pub height: u64,
    pub time: u64,
    pub root: &'a [u8; 32],
    pub tx_lengths: &'a [u32],
    pub tx_blob: &'a [u8],
}

impl<'a> Default for BlockInput<'a> {
    fn default() -> Self {
        BlockInput {
            parent: &[0u8; 32],
            height: 0,
            time: 0,
            root: &[0u8; 32],
            tx_lengths: &[],
            tx_blob: &[],
        }
    }
}

/// Write a Block into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_block(b: &mut zap::Builder, input: &BlockInput<'_>) -> usize {
    let mut list_tx_lengths = b.start_list();
    for elem in input.tx_lengths {
        list_tx_lengths.add_u32(b, *elem);
    }
    let at_tx_lengths = list_tx_lengths.finish_offset();
    let mut ob = b.start_object(BLOCK_SIZE);
    ob.set_bytes_fixed(b, BLOCK_PARENT, input.parent);
    ob.set_u64(b, BLOCK_HEIGHT, input.height);
    ob.set_u64(b, BLOCK_TIME, input.time);
    ob.set_bytes_fixed(b, BLOCK_ROOT, input.root);
    ob.set_list(b, BLOCK_TX_LENGTHS, at_tx_lengths, input.tx_lengths.len());
    ob.set_bytes(b, BLOCK_TX_BLOB, input.tx_blob);
    ob.finish(b)
}

/// Write a Block message and answer its bytes.
pub fn new_block(input: &BlockInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_block(&mut b, input);
    b.set_root(at);
    b.finish()
}

