# TAG should identify the builder image
ARG TAG

# ============= Compilation Stage ================
FROM antithesis-node-builder:$TAG AS builder

# The workdir is hard-coded since this Dockerfile is only intended for instrumented builds.
WORKDIR /node_instrumented/customer

# Build node with race detection (-r) enabled.
RUN ./scripts/build.sh -r

# ============= Cleanup Stage ================
FROM debian:11-slim AS execution

# Copy identifying information into the container
COPY --from=builder /build/commit_hash.txt ./commit_hash.txt

# Copy the antithesis dependencies into the container
RUN mkdir -p /symbols
COPY --from=builder /node_instrumented/symbols /symbols
COPY --from=builder /opt/antithesis/lib/libvoidstar.so /usr/lib/libvoidstar.so

# Use the same path as the uninstrumented node image for consistency
WORKDIR /node/build

# Copy the executable into the container
COPY --from=builder /node_instrumented/customer/build/node ./node

CMD [ "./node" ]
