apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lux-mainnet

resources:
- namespace.yaml
- services.yaml
- statefulset.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: luxd
  app.kubernetes.io/instance: mainnet
  app.kubernetes.io/component: validator
