# TAG should identify the builder image
ARG TAG

# LUXD_NODE_IMAGE needs to identify an existing node node image and should include the tag
ARG LUXD_NODE_IMAGE

# ============= Compilation Stage ================
FROM antithesis-node-builder:$TAG AS builder

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

WORKDIR $BUILDER_WORKDIR

# Build xsvm VM
RUN ./scripts/build_xsvm.sh

# ============= Cleanup Stage ================
FROM $LUXD_NODE_IMAGE AS execution

# The commit hash and antithesis dependencies should be part of the base image.

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

# Copy the executable into the container
RUN mkdir -p /root/.node/plugins
COPY --from=builder $BUILDER_WORKDIR/build/xsvm \
    /root/.node/plugins/v3m4wPxaHpvGr8qfMeyK6PRW3idZrPHmYcMTt7oXdK47yurVH

# The node image's entrypoint will be reused.
