// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/luxfi/node/quasar/engine/dag/vertex (interfaces: LinearizableVertex)
//
// Generated by this command:
//
//	mockgen -package=vertexmock -destination=vertexmock/linearizable_vertex.go -mock_names=LinearizableVertex=LinearizableVertex . LinearizableVertex
//

// Package vertexmock is a generated GoMock package.
package vertexmock

import (
	context "context"
	reflect "reflect"

	ids "github.com/luxfi/ids"
	choices "github.com/luxfi/node/quasar/choices"
	gomock "go.uber.org/mock/gomock"
)

// LinearizableVertex is a mock of LinearizableVertex interface.
type LinearizableVertex struct {
	ctrl     *gomock.Controller
	recorder *LinearizableVertexMockRecorder
	isgomock struct{}
}

// LinearizableVertexMockRecorder is the mock recorder for LinearizableVertex.
type LinearizableVertexMockRecorder struct {
	mock *LinearizableVertex
}

// NewLinearizableVertex creates a new mock instance.
func NewLinearizableVertex(ctrl *gomock.Controller) *LinearizableVertex {
	mock := &LinearizableVertex{ctrl: ctrl}
	mock.recorder = &LinearizableVertexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *LinearizableVertex) EXPECT() *LinearizableVertexMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *LinearizableVertex) Accept() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept")
	ret0, _ := ret[0].(error)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *LinearizableVertexMockRecorder) Accept() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*LinearizableVertex)(nil).Accept))
}

// Bytes mocks base method.
func (m *LinearizableVertex) Bytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes.
func (mr *LinearizableVertexMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*LinearizableVertex)(nil).Bytes))
}

// Epoch mocks base method.
func (m *LinearizableVertex) Epoch() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Epoch")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// Epoch indicates an expected call of Epoch.
func (mr *LinearizableVertexMockRecorder) Epoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Epoch", reflect.TypeOf((*LinearizableVertex)(nil).Epoch))
}

// Height mocks base method.
func (m *LinearizableVertex) Height() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *LinearizableVertexMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*LinearizableVertex)(nil).Height))
}

// ID mocks base method.
func (m *LinearizableVertex) ID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *LinearizableVertexMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*LinearizableVertex)(nil).ID))
}

// Linearize mocks base method.
func (m *LinearizableVertex) Linearize(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Linearize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Linearize indicates an expected call of Linearize.
func (mr *LinearizableVertexMockRecorder) Linearize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Linearize", reflect.TypeOf((*LinearizableVertex)(nil).Linearize), arg0)
}

// Parents mocks base method.
func (m *LinearizableVertex) Parents() ([]ids.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parents")
	ret0, _ := ret[0].([]ids.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parents indicates an expected call of Parents.
func (mr *LinearizableVertexMockRecorder) Parents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parents", reflect.TypeOf((*LinearizableVertex)(nil).Parents))
}

// Reject mocks base method.
func (m *LinearizableVertex) Reject() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *LinearizableVertexMockRecorder) Reject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*LinearizableVertex)(nil).Reject))
}

// Status mocks base method.
func (m *LinearizableVertex) Status() choices.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(choices.Status)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *LinearizableVertexMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*LinearizableVertex)(nil).Status))
}

// Timestamp mocks base method.
func (m *LinearizableVertex) Timestamp() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *LinearizableVertexMockRecorder) Timestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*LinearizableVertex)(nil).Timestamp))
}

// Verify mocks base method.
func (m *LinearizableVertex) Verify(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *LinearizableVertexMockRecorder) Verify(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*LinearizableVertex)(nil).Verify), arg0)
}
