// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/messenger/messenger.proto

package messenger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED   MessageType = 0
	MessageType_MESSAGE_TYPE_PENDING_TXS   MessageType = 1
	MessageType_MESSAGE_TYPE_PUT_BLOCK     MessageType = 2
	MessageType_MESSAGE_TYPE_GET_BLOCK     MessageType = 3
	MessageType_MESSAGE_TYPE_GET_ACCEPTED  MessageType = 4
	MessageType_MESSAGE_TYPE_ACCEPTED      MessageType = 5
	MessageType_MESSAGE_TYPE_GET_ANCESTORS MessageType = 6
	MessageType_MESSAGE_TYPE_MULTI_PUT     MessageType = 7
	MessageType_MESSAGE_TYPE_GET_FAILED    MessageType = 8
	MessageType_MESSAGE_TYPE_QUERY_FAILED  MessageType = 9
	MessageType_MESSAGE_TYPE_CHITS         MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_PENDING_TXS",
		2:  "MESSAGE_TYPE_PUT_BLOCK",
		3:  "MESSAGE_TYPE_GET_BLOCK",
		4:  "MESSAGE_TYPE_GET_ACCEPTED",
		5:  "MESSAGE_TYPE_ACCEPTED",
		6:  "MESSAGE_TYPE_GET_ANCESTORS",
		7:  "MESSAGE_TYPE_MULTI_PUT",
		8:  "MESSAGE_TYPE_GET_FAILED",
		9:  "MESSAGE_TYPE_QUERY_FAILED",
		10: "MESSAGE_TYPE_CHITS",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":   0,
		"MESSAGE_TYPE_PENDING_TXS":   1,
		"MESSAGE_TYPE_PUT_BLOCK":     2,
		"MESSAGE_TYPE_GET_BLOCK":     3,
		"MESSAGE_TYPE_GET_ACCEPTED":  4,
		"MESSAGE_TYPE_ACCEPTED":      5,
		"MESSAGE_TYPE_GET_ANCESTORS": 6,
		"MESSAGE_TYPE_MULTI_PUT":     7,
		"MESSAGE_TYPE_GET_FAILED":    8,
		"MESSAGE_TYPE_QUERY_FAILED":  9,
		"MESSAGE_TYPE_CHITS":         10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messenger_messenger_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_messenger_messenger_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messenger_messenger_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=messenger.MessageType" json:"type,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_messenger_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_messenger_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_messenger_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_messenger_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_proto_messenger_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_messenger_messenger_proto_rawDescGZIP(), []int{2}
}

var File_proto_messenger_messenger_proto protoreflect.FileDescriptor

const file_proto_messenger_messenger_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/messenger/messenger.proto\x12\tmessenger\"h\n" +
	"\aMessage\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.messenger.MessageTypeR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"=\n" +
	"\rNotifyRequest\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.messenger.MessageR\amessage\"\x10\n" +
	"\x0eNotifyResponse*\xcb\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MESSAGE_TYPE_PENDING_TXS\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_PUT_BLOCK\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_TYPE_GET_BLOCK\x10\x03\x12\x1d\n" +
	"\x19MESSAGE_TYPE_GET_ACCEPTED\x10\x04\x12\x19\n" +
	"\x15MESSAGE_TYPE_ACCEPTED\x10\x05\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_GET_ANCESTORS\x10\x06\x12\x1a\n" +
	"\x16MESSAGE_TYPE_MULTI_PUT\x10\a\x12\x1b\n" +
	"\x17MESSAGE_TYPE_GET_FAILED\x10\b\x12\x1d\n" +
	"\x19MESSAGE_TYPE_QUERY_FAILED\x10\t\x12\x16\n" +
	"\x12MESSAGE_TYPE_CHITS\x10\n" +
	"2J\n" +
	"\tMessenger\x12=\n" +
	"\x06Notify\x12\x18.messenger.NotifyRequest\x1a\x19.messenger.NotifyResponseB*Z(github.com/luxfi/node/proto/pb/messengerb\x06proto3"

var (
	file_proto_messenger_messenger_proto_rawDescOnce sync.Once
	file_proto_messenger_messenger_proto_rawDescData []byte
)

func file_proto_messenger_messenger_proto_rawDescGZIP() []byte {
	file_proto_messenger_messenger_proto_rawDescOnce.Do(func() {
		file_proto_messenger_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messenger_messenger_proto_rawDesc), len(file_proto_messenger_messenger_proto_rawDesc)))
	})
	return file_proto_messenger_messenger_proto_rawDescData
}

var file_proto_messenger_messenger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messenger_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_messenger_messenger_proto_goTypes = []any{
	(MessageType)(0),       // 0: messenger.MessageType
	(*Message)(nil),        // 1: messenger.Message
	(*NotifyRequest)(nil),  // 2: messenger.NotifyRequest
	(*NotifyResponse)(nil), // 3: messenger.NotifyResponse
}
var file_proto_messenger_messenger_proto_depIdxs = []int32{
	0, // 0: messenger.Message.type:type_name -> messenger.MessageType
	1, // 1: messenger.NotifyRequest.message:type_name -> messenger.Message
	2, // 2: messenger.Messenger.Notify:input_type -> messenger.NotifyRequest
	3, // 3: messenger.Messenger.Notify:output_type -> messenger.NotifyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_messenger_messenger_proto_init() }
func file_proto_messenger_messenger_proto_init() {
	if File_proto_messenger_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messenger_messenger_proto_rawDesc), len(file_proto_messenger_messenger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messenger_messenger_proto_goTypes,
		DependencyIndexes: file_proto_messenger_messenger_proto_depIdxs,
		EnumInfos:         file_proto_messenger_messenger_proto_enumTypes,
		MessageInfos:      file_proto_messenger_messenger_proto_msgTypes,
	}.Build()
	File_proto_messenger_messenger_proto = out.File
	file_proto_messenger_messenger_proto_goTypes = nil
	file_proto_messenger_messenger_proto_depIdxs = nil
}
