// Code generated by zip; DO NOT EDIT.

package genesis

import (
	"encoding/binary"
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- Allocation --------------------------------------------------------

const (
	allocationAddressAt = 0
	allocationBalanceAt = 24
	allocationSize      = 32
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Allocation)(nil)

// MarshalZAP writes Allocation from constant offsets.
func (x *Allocation) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(allocationSize + 256)
	ob := b.StartObject(allocationSize)
	ob.SetBytesFixed(allocationAddressAt, x.Address[:])
	ob.SetUint64(allocationBalanceAt, uint64(x.Balance))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Allocation out of the buffer that arrived.
func (x *Allocation) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Allocation: %w", err)
	}
	o := m.Root()
	copy(x.Address[:], o.BytesFixed(allocationAddressAt, 20))
	x.Balance = uint64(o.Uint64(allocationBalanceAt))
	return nil
}

// ---- Genesis -----------------------------------------------------------

const (
	genesisTimestampAt   = 0
	genesisAllocationsAt = 8
	genesisSize          = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Genesis)(nil)

// MarshalZAP writes Genesis from constant offsets.
func (x *Genesis) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(genesisSize + 256)
	allocationsAt, allocationsN := 0, len(x.Allocations)
	if allocationsN > 0 {
		var blob []byte
		for i := range x.Allocations {
			enc, err := x.Allocations[i].MarshalZAP()
			if err != nil {
				return nil, err
			}
			var n [4]byte
			binary.LittleEndian.PutUint32(n[:], uint32(len(enc)))
			blob = append(blob, n[:]...)
			blob = append(blob, enc...)
		}
		allocationsAt = b.WriteBytes(blob)
	}
	ob := b.StartObject(genesisSize)
	ob.SetInt64(genesisTimestampAt, int64(x.Timestamp))
	if allocationsN > 0 {
		ob.SetList(genesisAllocationsAt, allocationsAt, allocationsN)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Genesis out of the buffer that arrived.
func (x *Genesis) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Genesis: %w", err)
	}
	o := m.Root()
	x.Timestamp = int64(o.Int64(genesisTimestampAt))
	if l := o.List(genesisAllocationsAt); l.Len() > 0 {
		rows := make([]Allocation, l.Len())
		for i := range rows {
			if err := rows[i].UnmarshalZAP(l.BytesAt(i)); err != nil {
				return err
			}
		}
		x.Allocations = rows
	}
	return nil
}
