apiVersion: v1
kind: Service
metadata:
  name: luxd
spec:
  selector:
    app: luxd
  ports:
  - name: http
    port: 9630
    targetPort: 9630
    protocol: TCP
  - name: staking
    port: 9631
    targetPort: 9631
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: luxd-headless
spec:
  selector:
    app: luxd
  ports:
  - name: http
    port: 9630
    protocol: TCP
  - name: staking
    port: 9631
    protocol: TCP
  clusterIP: None
