// SPDX-License-Identifier: BSD-3-Clause-Eco
// Copyright (C) 2019-2026, Lux Industries Inc. All rights reserved.

//! Every P vector in the shared corpus, written back byte for byte.
//!
//! The corpus was generated by the Go chain, so a vector's hex is what Go
//! wrote. Reading one and writing it again has to reproduce it exactly: this
//! chain's writer and Go's are the same writer or they are not. That is what
//! makes the corpus a check on the WRITE path and not only on the read path —
//! a reader can agree about every field of bytes it could never have produced.
//!
//! `Tx::parse` and `Block::parse` are byte-preserving: each keeps the bytes
//! that arrived, so asking either for its bytes would prove nothing. These
//! tests go back through the BUILDER — the transaction is re-encoded from the
//! values that were read, and the block is rebuilt from those transactions.
//!
//! A ZAP message carries its own length, so a vector may hold bytes past the
//! end of the message and still parse. What a writer writes is the message:
//! where a vector is a message and nothing else the two are the same bytes,
//! and where it is not, the message is its prefix. A rewrite LONGER than its
//! vector, or one that disagrees anywhere inside the message, is the bytes
//! moving, and fails here.

use std::path::PathBuf;

use lux_platformvm::block::{Block, Kind};
use lux_platformvm::txs::Tx;

fn corpus() -> String {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../conformance/corpus/vectors.tsv");
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

fn unhex(s: &str) -> Option<Vec<u8>> {
    if s == "-" || s.len() % 2 != 0 {
        return None;
    }
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).ok())
        .collect()
}

/// The bytes this chain would write for a transaction it just read.
fn rewritten(tx: &Tx) -> Vec<u8> {
    Tx::new(tx.unsigned.clone(), tx.creds.clone()).bytes().to_vec()
}

/// The bytes this chain would write for a block it just read, out of
/// transactions it wrote itself rather than the ones it was handed.
fn rebuilt(b: &Block) -> Vec<u8> {
    let txs: Vec<Tx> = b
        .decision_txs()
        .iter()
        .map(|t| Tx::parse(&rewritten(t)).expect("rewritten tx parses"))
        .collect();
    match b.kind() {
        Kind::Standard => Block::standard(b.parent(), b.height(), b.timestamp(), txs),
        Kind::Proposal => {
            let tx = b.proposal_tx().expect("a proposal block carries one");
            let tx = Tx::parse(&rewritten(tx)).expect("rewritten proposal parses");
            Block::proposal(b.parent(), b.height(), b.timestamp(), tx)
        }
        Kind::Commit => Block::commit(b.parent(), b.height(), b.timestamp()),
        Kind::Abort => Block::abort(b.parent(), b.height(), b.timestamp()),
    }
    .bytes()
    .to_vec()
}

/// Whether a rewrite and the vector it came from are the same message.
fn is_the_same_message(id: &str, again: &[u8], vector: &[u8]) -> bool {
    assert!(
        again.len() <= vector.len(),
        "{id}: the rewrite is LONGER than the vector — the bytes moved"
    );
    let differ: Vec<usize> = (0..again.len()).filter(|&i| again[i] != vector[i]).collect();
    assert!(differ.is_empty(), "{id}: bytes moved at {differ:?}");
    again.len() == vector.len()
}

#[test]
fn every_p_vector_is_written_back_exactly_as_it_arrived() {
    let text = corpus();
    let (mut blocks, mut txs, mut exact) = (0, 0, 0);
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        if f.len() < 5 || f[0] != "V" || f[2] != "P" {
            continue;
        }
        let (id, op) = (f[1], f[3]);
        let Some(bytes) = unhex(f[4]) else { continue };

        match op {
            "tx" => {
                let Ok(tx) = Tx::parse(&bytes) else { continue };
                let again = rewritten(&tx);
                if is_the_same_message(id, &again, &bytes) {
                    exact += 1;
                }
                // Whatever the vector carried, the writer settles on one
                // answer: writing what was written changes nothing.
                let once_more = rewritten(&Tx::parse(&again).expect("the rewrite parses"));
                assert_eq!(once_more, again, "{id}: writing twice is not writing once");
                txs += 1;
            }
            "block" => {
                let Ok(b) = Block::parse(&bytes) else { continue };
                let again = rebuilt(&b);
                if is_the_same_message(id, &again, &bytes) {
                    exact += 1;
                    // A block's id is over its bytes, so identical bytes have
                    // to be identically named.
                    assert_eq!(
                        Block::parse(&again).expect("the rebuild parses").id(),
                        b.id(),
                        "{id}: block id moved"
                    );
                }
                blocks += 1;
            }
            _ => {}
        }
    }
    // A corpus that stopped naming P vectors would pass every assertion above.
    assert!(txs > 0, "no P transaction vector was read back");
    assert!(blocks > 0, "no P block vector was read back");
    println!(
        "{txs} P transactions and {blocks} P blocks read back; \
         {exact} of them are the message and nothing else, written back byte for byte"
    );
}
