name: Lint proto files

on:
  push:

permissions:
  contents: read

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
          version: "1.47.2"
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
