name: buf-push

on:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev
    paths:
      - "proto/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c #v1.3.0
        with:
          input: "proto"
          # Breaking changes are managed by the rpcchainvm protocol version.
          breaking: false
          token: ${{ secrets.BUF_TOKEN }}
          # This version should match the version installed in the nix dev shell
          version: 1.47.2
