name: buf-push

on:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev
    paths:
      - "proto/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@c231a1aa9281e5db706c970f468f0744a37561fd #v1.2.0
        with:
          input: "proto"
          # Breaking changes are managed by the rpcchainvm protocol version.
          breaking: false
          token: ${{ secrets.BUF_TOKEN }}
          # This version should match the version installed in the nix dev shell
          version: 1.47.2
