name: Build + Test Mac-Windows

on:
  push:
    tags:
      - "*" # Push events to every tag
    branches:
      - main
      - dev
      - master

jobs:
  run_build_tests:
    name: build_tests
    runs-on: ${{ matrix.os }}
    env:
      GOPRIVATE: github.com/luxfi/*
      GONOSUMDB: github.com/luxfi/*
      CGO_ENABLED: "0"
      GOWORK: off
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go-for-project
      - name: build_test
        shell: bash
        run: .github/workflows/build_and_test.sh
