# https://goreleaser.com/ci/actions/
# TODO: replace other build github actions
name: Build on supported platforms

on:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go-for-project
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.13.1
          # TODO: automate github release page announce and artifact uploads
          # https://goreleaser.com/cmd/goreleaser_release/
          args: release --rm-dist --skip-announce --skip-publish

        # to automate release announcement
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        # env:
        # GITHUB_TOKEN: ...
