# Build a windows release from the node repo

name: build-win-release

# Controls when the action will run.
on:
  workflow_dispatch:
  push:
    tags:
      - "*" # Push events to every tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-2019
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go-for-project
      - run: go version

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Install awscli
        run: |
          msiexec.exe /passive /i /n https://awscli.amazonaws.com/AWSCLIV2.msi 
          aws --version

      # Runs a single command using the runners shell
      - name: Build the node binary
        run: ./scripts/build.sh
        shell: bash

      - name: Create zip
        run: |
          mv .\build\node .\build\node.exe
          Compress-Archive -Path .\build\node.exe -DestinationPath .\build\node-win-${{ env.VERSION }}-experimental.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy to s3
        run: aws s3 cp .\build\node-win-${{ env.VERSION }}-experimental.zip s3://${{ secrets.BUCKET }}/windows/node-win-${{ env.VERSION }}-experimental.zip
