name: Run fuzz tests

on:
  schedule:
    - cron: "0 0 * * *" # Once a day at midnight UTC

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: lux-build-amd64
    env:
      GOPRIVATE: github.com/luxfi/*
      GONOSUMDB: github.com/luxfi/*
      GOWORK: off
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: ./.github/actions/setup-go-for-project
      - name: Configure Git for private modules
        shell: bash
        run: git config --global url."https://${{ github.token }}@github.com/".insteadOf "https://github.com/"
      - name: Run fuzz tests
        shell: bash
        run: ./scripts/build_fuzz.sh 180 # Run each fuzz test 180 seconds
        env:
          CGO_ENABLED: '0'
