name: Static analysis
on:
  push:
    tags-ignore:
      - "*" # Ignores all tags
    branches-ignore:
      - master
      - dev

jobs:
  run_static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go-for-project
      - name: Run static analysis tests
        shell: bash
        run: scripts/lint.sh
