name: Test e2e

on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go-for-project
      - name: Build the node binary
        shell: bash
        run: ./scripts/build.sh -r
      - name: Run e2e tests
        shell: bash
        run: scripts/tests.e2e.sh ./build/luxd
      - name: Run e2e tests for whitelist vtx
        shell: bash
        run: ENABLE_WHITELIST_VTX_TESTS=true ./scripts/tests.e2e.sh ./build/luxd
