// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/luxfi/node/vms/platformvm/state (interfaces: Versions)
//
// Generated by this command:
//
//	mockgen -package=state -destination=mock_versions.go . Versions
//

// Package state is a generated GoMock package.
package state

import (
	reflect "reflect"

	ids "github.com/luxfi/ids"
	gomock "go.uber.org/mock/gomock"
)

// MockVersions is a mock of Versions interface.
type MockVersions struct {
	ctrl     *gomock.Controller
	recorder *MockVersionsMockRecorder
	isgomock struct{}
}

// MockVersionsMockRecorder is the mock recorder for MockVersions.
type MockVersionsMockRecorder struct {
	mock *MockVersions
}

// NewMockVersions creates a new mock instance.
func NewMockVersions(ctrl *gomock.Controller) *MockVersions {
	mock := &MockVersions{ctrl: ctrl}
	mock.recorder = &MockVersionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersions) EXPECT() *MockVersionsMockRecorder {
	return m.recorder
}

// GetState mocks base method.
func (m *MockVersions) GetState(blkID ids.ID) (Chain, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", blkID)
	ret0, _ := ret[0].(Chain)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockVersionsMockRecorder) GetState(blkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockVersions)(nil).GetState), blkID)
}
